### ISSUE TITLE
not work pip install dataclasses_json paho-mqtt pycryptodome

### ISSUE THREAD

**Issue by wifi75** [deiger/AirCon#10]
Hello on my ubuntu I have already installed library 
pip install dataclasses_json paho-mqtt pycryptodome
but after run coomand  
./hisense.py --port 8888 --ip 192.168.1.235 --config config.json --mqtt_host 192.168.1.52 --mqtt_user ioufoidsflk:dauysgdjsahfdthere is this error;

> Traceback (most recent call last):
>   File "./hisense.py", line 36, in <module>
>     from dataclasses_json import dataclass_json
> ModuleNotFoundError: No module named 'dataclasses_json'

why?
```

**Comment by deiger** [comment]
This might be an issue with Python2 vs Python3.
Try running `pip3 install dataclasses_json paho-mqtt pycryptodome`. Also, you may want to run this under `sudo`, to install for all users.
