### ISSUE TITLE
quiet mode Switch will not work

### ISSUE THREAD

**Issue by Pirol62** [deiger/AirCon#100]
Hi,
I already managed to install the TQ2 AC and it works.
The climate entity does not provide the quiet mode (t_fan_mute)
![image](https://user-images.githubusercontent.com/48820003/118003850-3a7a2500-b349-11eb-81f3-393fd7206365.png)
So I created a swicht:
````
- platform: mqtt
  name: "Klima Ruhemodus"
  command_topic: "hisense_ac/t_fan_mute/command"
  state_topic: "hisense_ac/t_fan_mute/status"
  payload_on: "on"
  payload_off: "off"
  qos: 1
````
that switch does not work. 
I guess, that it has something to to with the topic.
I tried a lot instead of hisense_ac with the publish service. Nothing helps

Can someone push me into the right direction where this topic comes from?
I have no further idea

**Comment by hzpz** [comment]
Tip: By listening to every MQTT message Home Assistant receives, you might be able to find the correct topic. 

From the Home Assistant docs:
> Choose the “Configuration” tab, click “Integrations” and click the “Configure” option under the “MQTT” integration. 
> [...]
> In the “Listen to a topic” field, type # to see everything [...]

(Source: https://www.home-assistant.io/docs/mqtt/testing/)

**Comment by Pirol62** [comment]
Thank you hzpz. That was the game changer!

**Comment by fixsssator** [comment]
> Thank you hzpz. That was the game changer!

Hello, please help, i want to create quiet switch too, how did you do that?
