### ISSUE TITLE
Can't set sleep mode nor dimmer (turn led off)

### ISSUE THREAD

**Issue by MadDoct** [deiger/AirCon#101]
LOG:

```
I0514 11:18:10.861  mqtt_client.py:37] MQTT message Topic: hisense_ac/ca2c4f949e89/t_sleep/command, Payload b'stop'
E0514 11:18:10.862  aircon.py:500] Cannot convert to control value property t_sleep
E0514 11:18:10.862  mqtt_client.py:56] Failed to parse value STOP for property t_sleep
Traceback (most recent call last):
  File "/app/aircon/mqtt_client.py", line 53, in mqtt_on_message
    chosen_device.queue_command(prop_name, payload.upper())
  File "/app/aircon/aircon.py", line 274, in queue_command
    super().queue_command(name, value)
  File "/app/aircon/aircon.py", line 169, in queue_command
    self._convert_to_control_value(name, data_value)
  File "/app/aircon/aircon.py", line 501, in _convert_to_control_value
    raise ValueError()
ValueError
```

**Comment by hzpz** [comment]
It seems to me that only `t_power`, `t_fan_speed`, `t_work_mode`, `t_temp_heatcold`, `t_eco`, `t_temp`, `t_fan_power`, `t_fan_leftright`, `t_fan_mute` and `t_temptype` are implemented (see [_convert_to_control_value](https://github.com/deiger/AirCon/blob/32fdccf6d5e003c6b4dfe1dfee5fc282dd96add6/aircon/aircon.py#L478)), but I am not sure I understand all of the code.

**Comment by deiger** [comment]
Can you provide more details? Which A/C are you using, which app etc?
Does you A/C actually supports that functionality?
Some A/Cs concentrate their control in a unified `t_control_value`, however `t_sleep` isn't part of it in the cases I've seen.

**Comment by MadDoct** [comment]
I'm using Hisense Luso units (hisense confort), split 1x1.
3 units. All show the same behaviour. app is hisense-eu.
The addon reports t_sleep as "stop", independently of the setting I selected usindg the remote but maybe that doesn't mean anything...
They have 4 sleep modes and have Dimmer (LED off) options on the remote and those work...
Maybe it is related to what @hzpz said...

**Comment by Pirol62** [comment]
I can support this. t_sleep and t_backlight not working as mentioned in my connected issue which I close now.
In addition I detected that the fan mode does not change when setting the quiet mode.
In the app, the fan mode is on lower in this case.

**Comment by phm46** [comment]
@deiger My A/C supports `t_sleep` functionality and it's controlled by `t_sleep` value and not `t_control_value`. I quickly modified source code to fire `t_sleep` value change and it was changed immediately. So it should be easily modified - I'll try to create PR.
