### ISSUE TITLE
Sleep mode or display off - no property works

### ISSUE THREAD

**Issue by Pirol62** [deiger/AirCon#105]
Hi,

basically my integration works.
I manage the AC via automations and have one switch, which sets the quiet mode:
````
- platform: mqtt
  name: "Klima Ruhemodus"
  command_topic: "hisense_ac/ca2c4fa285af/t_fan_mute/command"
  state_topic: "hisense_ac/ca2c4fa285af/t_fan_mute/status"
  payload_on: "on"
  payload_off: "off"
  qos: 1
````

My last big issue is, that I want to switch off the display or alternatively set the sleep mode to four.

So I created a second switch for t_backlight:
````
- platform: mqtt
  name: "Klima Display"
  command_topic: "hisense_ac/ca2c4fa285af/t_backlight/command"
  state_topic: "hisense_ac/ca2c4fa285af/t_backlight/status"
  payload_on: "on"
  payload_off: "off"
  qos: 1
````
Watching the messages, the command goes out but is ignored by the AC.
t_sleep as well. I receive mqtt messages, that t_sleep is set to four. But it is not possible, to switch it on or off.
A switch with the payload_on: four and payload_off: stop  did not work.

Has anybody realized that? Or do I have a wrong expectation on these properties?

**Comment by hzpz** [comment]
Possible duplicate of #101.

**Comment by Pirol62** [comment]
yep, sorry. I close this and follow #101

**Comment by wifi75** [comment]
Yeahhh!
