### ISSUE TITLE
typo in code. expected: f_voltage got: f_votage

### ISSUE THREAD

**Issue by Lucus123** [deiger/AirCon#108]
theres a typo in the query_handlers.py that incorrectly states **f_voltage** as **f_votage**

see:

I0531 16:39:55.046  query_handlers.py:136] Decrypted: {"seq_no":5100,"data":{"name":"f_votage","value":226}}
E0531 16:39:55.050  query_handlers.py:89] Failed to handle {'seq_no': 5100, 'data': {'name': 'f_votage', 'value': 226}}. Exception = 'f_votage'

**Comment by deiger** [comment]
Yuck. That's actually a typo in the A/C. The code state `f_voltage`. Also mentioned in #36.
