### ISSUE TITLE
UnicodeDecodeError in query_cli

### ISSUE THREAD

**Issue by dvdavide** [deiger/AirCon#11]
Hi,
I was trying to recreate the config.json and I got this error:

```
Traceback (most recent call last):
  File "./query_cli.py", line 145, in <module>
    tokens = json.loads(resp.read())
  File "/usr/lib/python3.7/json/__init__.py", line 343, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```
My password doesn't have any strange characters in it and my credentials should be correct (if I change them I get a 401 response). I tried the script both on ubuntu and in windows, same result.

Now I don't know if it's a problem with the servers or with a python update (ubuntu is on python 3.7.7, windows on python 3.7.4) or if I'm just making some stupid error I am failing to see. Any help would be much appreciated. Thank you.

**Comment by deiger** [comment]
Seems that the issue is with the response from their site. I changed the code to print the response in case of an error, so please try again.

**Comment by dvdavide** [comment]
Thanks for your reply! I have tried running the updated version of the script, this is the response i receive:

`E0316 22:52:22.544  query_cli.py:150] Failed to parse login tokens to Hisense server:
Data: b"\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\x03<\xcc\xc1\n\xc20
[...]
\xe6\xfa\xb2<Q\xf1iN\xe7\x82\x8d~C\xd8\xf5Vh\xbc\\?_\x00\x00\x00\xff\xff\x03\x00\xb1\x03;\xc9\x99\x00\x00\x00"

Traceback (most recent call last):
  File "./query_cli.py", line 147, in <module>
    tokens = json.loads(resp_data)
  File "/usr/lib/python3.7/json/__init__.py", line 343, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte`

I tried connecting with two different apps (oem-eu and hisense-eu, I have one W4B1 and a few W4E1) and other than a slightly different token string, the response was the same in both cases.

**Comment by deiger** [comment]
Ah, got it. Their server suddenly supports gzip. Fixed the script to handle that.
