### ISSUE TITLE
error when I try to launch the docker

### ISSUE THREAD

**Issue by domoticluca** [deiger/AirCon#122]
I’ve an Hisense air conditioner with wifi module AEH-W4E1,
I tried to use this component to integrate the air conditioner in home assistant core trough Docker on a raspberry pi4
but it does not work, I did not understand where I’ve to copy the file options.json
When I launch the docker compose I get the following error:
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/pi/docker-compose/Dockerfile: no such file or directory
ERROR: Service 'copy_config' failed to build : Build failed
Could you help me? what I’m doing wrong?

**Comment by domoticluca** [comment]
Issue solved, I forgot to clone the repository, but in my opinion the instructions are a little bit misleading for neophyte like me because is wrote:
**Download the docker-compose.yaml and options.json. Update all the relevant fields in options.json**
But in reality you have to clone the repository

> **sudo git clone https://github.com/deiger/AirCon**  

then you have to 

> **modify the file options.json** 

and in the end you have to 
**launch the docker**

**Comment by summer1090** [comment]
Even this issue is closed, I can say I had the same problem of misleading steps description.
