### ISSUE TITLE
Log error on HA ( Decrypted)

### ISSUE THREAD

**Issue by wifi75** [deiger/AirCon#127]
Hello I have foud this error, 
```

0822 15:53:31.345  query_handlers.py:136] Decrypted: {"seq_no":10268,"data":{"name":"f_electricity","value":3}}
I0822 15:53:31.347  web_log.py:206] 192.168.1.18 [22/Aug/2021:13:53:31 +0000] "POST /local_lan/property/datapoint.json HTTP/1.1" 200 149 "-" "-"
```

what does it mean?

**Comment by hzpz** [comment]
What makes you think that this is an error? Afaik this is just the, well, decrypted value that was received from a device.

**Comment by deiger** [comment]
Indeed, this isn't an error. It's just a log message. The prefix I (info) indicates that. You can avoid these messages by changing the log level.
