### ISSUE TITLE
AC not visible in devices.

### ISSUE THREAD

**Issue by urgin** [deiger/AirCon#139]
Not sure of the configuration is fully correct however MQQT shows successful login, and the Hisense file is updating in the config.  

Tried putting IP to always the same fixed from the modem
removed the ac from the app  and re added it with a different name, the config file was deleted and it was updated with the new name.  however the ac is still not showing in devices.

The only new device i found in Devices was the Hisense Addon
![image](https://user-images.githubusercontent.com/37270724/145690993-ae9ee0e3-8660-4fa4-8f7d-73887f902c7e.png)

Appreciate if someone can help as i am really stuck.  

Config file data
{"name": "Air conditioner 1", "app": "hisense-eu", "model": "Smart-1-110-eu", "sw_version": "ADA 1.4.3-beta ameba 2018-03-28 19:20:06 8f40fe89d", "dsn": "AC000W006571769", "temp_type": "C", "mac_address": "ca2c4f5ea345", "ip_address": "192.168.0.233", "lanip_key": "**********", "lanip_key_id": ****}

Hisense AC logs
I1211 21:31:18.707  query_handlers.py:136] Decrypted: {"seq_no":63,"data":{"name":"f_e_outmachine","base_type":"boolean","value":0}}
I1211 21:31:18.713  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:18 +0000] "POST /local_lan/property/datapoint.json?cmd_id=62&status=200 HTTP/1.1" 200 149 "-" "-"
I1211 21:31:18.819  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:18 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I1211 21:31:18.853  query_handlers.py:136] Decrypted: {"seq_no":64,"data":{"name":"f_e_outtemp","base_type":"boolean","value":0}}
I1211 21:31:18.859  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:18 +0000] "POST /local_lan/property/datapoint.json?cmd_id=63&status=200 HTTP/1.1" 200 149 "-" "-"
I1211 21:31:19.069  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:19 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I1211 21:31:19.110  query_handlers.py:136] Decrypted: {"seq_no":65,"data":{"name":"f_e_outtemplow","base_type":"boolean","value":0}}
I1211 21:31:19.116  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:19 +0000] "POST /local_lan/property/datapoint.json?cmd_id=64&status=200 HTTP/1.1" 200 149 "-" "-"
I1211 21:31:19.143  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:19 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 461 "-" "-"
I1211 21:31:19.179  query_handlers.py:136] Decrypted: {"seq_no":66,"data":{"name":"f_e_push","base_type":"integer","value":0}}
I1211 21:31:19.185  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:19 +0000] "POST /local_lan/property/datapoint.json?cmd_id=65&status=200 HTTP/1.1" 200 149 "-" "-"
I1211 21:31:19.314  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:19 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I1211 21:31:19.348  query_handlers.py:136] Decrypted: {"seq_no":67,"data":{"name":"f_filterclean","base_type":"boolean","value":0}}
I1211 21:31:19.354  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:19 +0000] "POST /local_lan/property/datapoint.json?cmd_id=66&status=200 HTTP/1.1" 200 149 "-" "-"
I1211 21:31:19.460  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:19 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I1211 21:31:19.493  query_handlers.py:136] Decrypted: {"seq_no":68,"data":{"name":"f_humidity","base_type":"integer","value":0}}
I1211 21:31:19.499  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:19 +0000] "POST /local_lan/property/datapoint.json?cmd_id=67&status=200 HTTP/1.1" 200 149 "-" "-"
I1211 21:31:19.612  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:19 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I1211 21:31:19.646  query_handlers.py:136] Decrypted: {"seq_no":69,"data":{"name":"f_power_display","base_type":"integer","value":0}}
I1211 21:31:19.652  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:19 +0000] "POST /local_lan/property/datapoint.json?cmd_id=68&status=200 HTTP/1.1" 200 149 "-" "-"
I1211 21:31:19.760  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:19 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I1211 21:31:19.793  query_handlers.py:136] Decrypted: {"seq_no":70,"data":{"name":"f_temp_in","base_type":"integer","value":26}}
I1211 21:31:19.799  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:19 +0000] "POST /local_lan/property/datapoint.json?cmd_id=69&status=200 HTTP/1.1" 200 149 "-" "-"
I1211 21:31:19.905  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:19 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I1211 21:31:20.040  query_handlers.py:136] Decrypted: {"seq_no":71,"data":{}}
I1211 21:31:20.041  query_handlers.py:82] Unsupported update message = 71
I1211 21:31:20.045  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:20 +0000] "POST /local_lan/property/datapoint.json?cmd_id=70&status=404 HTTP/1.1" 200 149 "-" "-"
I1211 21:31:20.064  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:20 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I1211 21:31:20.098  query_handlers.py:136] Decrypted: {"seq_no":72,"data":{"name":"t_backlight","base_type":"boolean","value":0}}
I1211 21:31:20.104  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:20 +0000] "POST /local_lan/property/datapoint.json?cmd_id=71&status=200 HTTP/1.1" 200 149 "-" "-"
I1211 21:31:20.208  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:20 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I1211 21:31:20.348  query_handlers.py:136] Decrypted: {"seq_no":73,"data":{"name":"t_control_value","base_type":"integer","value":2753024}}
I1211 21:31:20.355  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:20 +0000] "POST /local_lan/property/datapoint.json?cmd_id=72&status=200 HTTP/1.1" 200 149 "-" "-"
I1211 21:31:20.373  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:20 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I1211 21:31:20.406  query_handlers.py:136] Decrypted: {"seq_no":74,"data":{"name":"t_device_info","base_type":"integer","value":0}}
I1211 21:31:20.412  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:20 +0000] "POST /local_lan/property/datapoint.json?cmd_id=73&status=200 HTTP/1.1" 200 149 "-" "-"
I1211 21:31:20.516  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:20 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I1211 21:31:20.550  query_handlers.py:136] Decrypted: {"seq_no":75,"data":{}}
I1211 21:31:20.552  query_handlers.py:82] Unsupported update message = 75
I1211 21:31:20.555  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:20 +0000] "POST /local_lan/property/datapoint.json?cmd_id=74&status=404 HTTP/1.1" 200 149 "-" "-"
I1211 21:31:20.663  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:20 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 461 "-" "-"
I1211 21:31:20.696  query_handlers.py:136] Decrypted: {"seq_no":76,"data":{}}
I1211 21:31:20.698  query_handlers.py:82] Unsupported update message = 76
I1211 21:31:20.702  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:20 +0000] "POST /local_lan/property/datapoint.json?cmd_id=75&status=404 HTTP/1.1" 200 149 "-" "-"
I1211 21:31:20.807  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:20 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I1211 21:31:20.940  query_handlers.py:136] Decrypted: {"seq_no":77,"data":{}}
I1211 21:31:20.942  query_handlers.py:82] Unsupported update message = 77
I1211 21:31:20.946  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:20 +0000] "POST /local_lan/property/datapoint.json?cmd_id=76&status=404 HTTP/1.1" 200 149 "-" "-"
I1211 21:31:21.076  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:21 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I1211 21:31:21.211  query_handlers.py:136] Decrypted: {"seq_no":78,"data":{}}
I1211 21:31:21.212  query_handlers.py:82] Unsupported update message = 78
I1211 21:31:21.216  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:21 +0000] "POST /local_lan/property/datapoint.json?cmd_id=77&status=404 HTTP/1.1" 200 149 "-" "-"
I1211 21:31:21.238  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:21 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I1211 21:31:21.289  query_handlers.py:136] Decrypted: {"seq_no":79,"data":{}}
I1211 21:31:21.291  query_handlers.py:82] Unsupported update message = 79
I1211 21:31:21.294  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:21 +0000] "POST /local_lan/property/datapoint.json?cmd_id=78&status=404 HTTP/1.1" 200 149 "-" "-"
I1211 21:31:21.325  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:21 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I1211 21:31:21.361  query_handlers.py:136] Decrypted: {"seq_no":80,"data":{}}
I1211 21:31:21.363  query_handlers.py:82] Unsupported update message = 80
I1211 21:31:21.368  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:21 +0000] "POST /local_lan/property/datapoint.json?cmd_id=79&status=404 HTTP/1.1" 200 149 "-" "-"
I1211 21:31:21.479  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:21 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I1211 21:31:21.514  query_handlers.py:136] Decrypted: {"seq_no":81,"data":{"name":"t_ftkt_start","base_type":"integer","value":0}}
I1211 21:31:21.520  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:21 +0000] "POST /local_lan/property/datapoint.json?cmd_id=80&status=200 HTTP/1.1" 200 149 "-" "-"
I1211 21:31:21.625  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:21 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 461 "-" "-"
I1211 21:31:21.657  query_handlers.py:136] Decrypted: {"seq_no":82,"data":{"name":"t_power","base_type":"boolean","value":0}}
I1211 21:31:21.665  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:21 +0000] "POST /local_lan/property/datapoint.json?cmd_id=81&status=200 HTTP/1.1" 200 149 "-" "-"
I1211 21:31:21.770  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:21 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I1211 21:31:21.804  query_handlers.py:136] Decrypted: {"seq_no":83,"data":{}}
I1211 21:31:21.805  query_handlers.py:82] Unsupported update message = 83
I1211 21:31:21.809  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:21 +0000] "POST /local_lan/property/datapoint.json?cmd_id=82&status=404 HTTP/1.1" 200 149 "-" "-"
I1211 21:31:21.918  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:21 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I1211 21:31:21.951  query_handlers.py:136] Decrypted: {"seq_no":84,"data":{}}
I1211 21:31:21.953  query_handlers.py:82] Unsupported update message = 84
I1211 21:31:21.957  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:21 +0000] "POST /local_lan/property/datapoint.json?cmd_id=83&status=404 HTTP/1.1" 200 149 "-" "-"
I1211 21:31:22.062  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:22 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 461 "-" "-"
I1211 21:31:22.097  query_handlers.py:136] Decrypted: {"seq_no":85,"data":{"name":"t_sleep","base_type":"integer","value":0}}
I1211 21:31:22.103  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:22 +0000] "POST /local_lan/property/datapoint.json?cmd_id=84&status=200 HTTP/1.1" 200 149 "-" "-"
I1211 21:31:22.209  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:22 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 461 "-" "-"
I1211 21:31:22.240  query_handlers.py:136] Decrypted: {"seq_no":86,"data":{}}
I1211 21:31:22.243  query_handlers.py:82] Unsupported update message = 86
I1211 21:31:22.246  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:22 +0000] "POST /local_lan/property/datapoint.json?cmd_id=85&status=404 HTTP/1.1" 200 149 "-" "-"
I1211 21:31:22.357  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:22 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I1211 21:31:22.392  query_handlers.py:136] Decrypted: {"seq_no":87,"data":{}}
I1211 21:31:22.394  query_handlers.py:82] Unsupported update message = 87
I1211 21:31:22.398  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:22 +0000] "POST /local_lan/property/datapoint.json?cmd_id=86&status=404 HTTP/1.1" 200 149 "-" "-"
I1211 21:31:22.505  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:22 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I1211 21:31:22.539  query_handlers.py:136] Decrypted: {"seq_no":88,"data":{}}
I1211 21:31:22.541  query_handlers.py:82] Unsupported update message = 88
I1211 21:31:22.545  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:22 +0000] "POST /local_lan/property/datapoint.json?cmd_id=87&status=404 HTTP/1.1" 200 149 "-" "-"
I1211 21:31:22.654  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:22 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I1211 21:31:22.685  query_handlers.py:136] Decrypted: {"seq_no":89,"data":{}}
I1211 21:31:22.686  query_handlers.py:82] Unsupported update message = 89
I1211 21:31:22.690  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:22 +0000] "POST /local_lan/property/datapoint.json?cmd_id=88&status=404 HTTP/1.1" 200 149 "-" "-"
I1211 21:31:22.803  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:22 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I1211 21:31:22.837  query_handlers.py:136] Decrypted: {"seq_no":90,"data":{"name":"t_work_mode","base_type":"integer","value":1}}
I1211 21:31:22.842  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:31:22 +0000] "POST /local_lan/property/datapoint.json?cmd_id=89&status=200 HTTP/1.1" 200 149 "-" "-"
I1211 21:33:04.935  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:33:04 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 269 "-" "-"
I1211 21:34:46.831  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:34:46 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 269 "-" "-"
I1211 21:36:28.508  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:36:28 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 269 "-" "-"
I1211 21:38:10.502  web_log.py:206] 192.168.0.233 [11/Dec/2021:20:38:10 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 269 "-" "-"

**Comment by deiger** [comment]
It seems you have an issue with your Mosquitto broker.
Try entering the devices list for the Mosquitto broker integration, and look for the air conditioner.
If you don't see it there, I'd suggest connecting to the broker using MQTT Explorer, and look up the data.

**Comment by urgin** [comment]
Re configured the MQTT broker and it worked

thanks for your input
Jurgen
