### ISSUE TITLE
Publish to unique MQTT topics

### ISSUE THREAD

**Issue by gilesmartin** [deiger/AirCon#15]
Hello - 

Thank you for your great work on this. I have the controller running in a docker container on my raspberry pi with Hass.io (home assistant) installed. This works ok and I am able to get some readings from the AC (current set temp, fan mode, etc) using the MQTT HVAC component (https://www.home-assistant.io/integrations/climate.mqtt/#current_temperature_topic)

but this component is really set up to receive status on individual MQTT topics rather than on one topic for status and one topic for command as the AirCon app currently does.

Would it be possible to modify the app to publish and receive commands on separate topics? this would make it much easier to integrate into HA.

Here is my current entry for the AC:

climate:
  - platform: mqtt
    name: "Bedroom Air Con"
    current_temperature_topic: "hisesnse_ac/status"
    current_temperature_template: "{{ value_json.f_temp_in }}"
    action_topic: "hisesnse_ac/status" 
    action_template: "{{ value_json.t_work_mode }}"
    fan_mode_command_topic: "hisense_ac/command"
    fan_mode_state_topic: "hisesnse_ac/status"
    fan_mode_state_template: "{{ value_json.t_fan_speed }}"
    fan_modes:
      - "AUTO"
      - "LOWER"
      - "LOW"
      - "MEDIUM"
      - "HIGH"
      - "HIGHER"
    mode_command_topic: "hisense_ac/command"
    mode_state_topic: "hisense_ac/status"
    mode_state_template: "{{ value_json.t_work_mode }}"
    modes:
      - "FAN"
      - "HEAT"
      - "COOL"
      - "DRY"
      - "AUTO"
    swing_mode_state_topic: "hisense_ac/status"
    swing_mode_command_topic: "hisense_ac/command"
    swing_mode_state_template: "{{ value_json.t_fan_power }}"
    temperature_command_topic: "hisense_ac/command"
    temperature_state_topic: "hisense_ac/status"
    temperature_state_template: "{{ value_json.t_temp }}"

**Comment by deiger** [comment]
Sure, it should be fairly simple to do that. I'll add the property to be part of the topic name.
It seems a bit strange that it doesn't support less than 2 x number of functions.

**Comment by deiger** [comment]
OK, updated it, including lowercasing, as well as switching from the AC's FAN to HA's fan_only.
Please try it out - I probably have missed something, as it was blind coding without testing.

**Comment by gilesmartin** [comment]
doesn't start:

Traceback (most recent call last):
  File "/usr/lib/hisense/hisense.py", line 749, in <module>
    _mqtt_topics['pub'] = '/'.join(_parsed_args.mqtt_topic, '{}', 'status')
TypeError: join() takes exactly one argument (3 given)

**Comment by deiger** [comment]
Right, just thought of this error and fixed it before reading your comment. :)
Should run now.

**Comment by gilesmartin** [comment]
great! seems to be working now. 
<img width="403" alt="image" src="https://user-images.githubusercontent.com/17094763/80926925-17d52980-8d4f-11ea-800a-e026b256cdde.png">

**Comment by gilesmartin** [comment]
is the command structure hisense_ac/<function>/command?

I am not getting a response when sending hisense_ac/t_temp/command 74.0

**Comment by gilesmartin** [comment]
but I am receiving hisense_ac/t_temp/status 75

**Comment by deiger** [comment]
t_temp is an integer, try passing it 74 rather than 74.0.
Also, do you see anything relevant in the log?

**Comment by deiger** [comment]
Changed the code to succeed parsing integers formatted as decimals, so 74.0 should work now as well.

**Comment by gilesmartin** [comment]
Still seems to only be responding to integer and not decimal (which HS uses). Here is the debug of the MQTT commands. first send (74.0) is from HA. Second send (74) is from me manually:


 _    _                                         _     _              _
| |  | |                          /\           (_)   | |            | |
| |__| | ___  _ __ ___   ___     /  \   ___ ___ _ ___| |_ __ _ _ __ | |_
|  __  |/ _ \| '_ ` _ \ / _ \   / /\ \ / __/ __| / __| __/ _` | '_ \| __|
| |  | | (_) | | | | | |  __/  / ____ \\__ \__ \ \__ \ || (_| | | | | |_
|_|  |_|\___/|_| |_| |_|\___| /_/    \_\___/___/_|___/\__\__,_|_| |_|\__|


Our command line:
$ ha help
➜  ~ mosquitto_sub -h 10.0.0.9 -t '#'
hisense_ac/f_electricity/status 0
hisense_ac/f_e_arkgrille/status False
hisense_ac/f_e_incoiltemp/status False
hisense_ac/f_e_incom/status False
hisense_ac/f_e_indisplay/status False
hisense_ac/f_e_ineeprom/status False
hisense_ac/f_e_inele/status False
hisense_ac/f_e_infanmotor/status False
hisense_ac/f_e_inhumidity/status False
hisense_ac/f_e_inkeys/status False
hisense_ac/f_e_inlow/status False
hisense_ac/f_e_intemp/status False
hisense_ac/f_e_invzero/status False
hisense_ac/f_e_outcoiltemp/status False
hisense_ac/f_e_outeeprom/status False
hisense_ac/f_e_outgastemp/status False
hisense_ac/f_e_outmachine2/status False
hisense_ac/f_e_outmachine/status False
hisense_ac/f_e_outtemp/status False
hisense_ac/f_e_outtemplow/status False
hisense_ac/f_e_push/status False
hisense_ac/f_filterclean/status False
hisense_ac/f_humidity/status 0
hisense_ac/f_power_display/status False
hisense_ac/f_temp_in/status 73.0
hisense_ac/f_voltage/status 0
hisense_ac/t_backlight/status off
hisense_ac/t_device_info/status False
hisense_ac/t_display_power/status False
hisense_ac/t_eco/status off
hisense_ac/t_fan_leftright/status off
hisense_ac/t_fan_mute/status off
hisense_ac/t_fan_power/status off
hisense_ac/t_fan_speed/status fan_only
hisense_ac/t_ftkt_start/status 0
hisense_ac/t_power/status on
hisense_ac/t_run_mode/status off
hisense_ac/t_setmulti_value/status 0
hisense_ac/t_sleep/status fan_only
hisense_ac/t_temp/status 75
hisense_ac/t_temptype/status fahrenheit
hisense_ac/t_temp_eight/status off
hisense_ac/t_temp_heatcold/status off
hisense_ac/t_work_mode/status cool
hisense_ac/t_temp/command 74.0
hisense_ac/t_temp/command 74
hisense_ac/t_temp/status 74

**Comment by deiger** [comment]
Can you check what appears in the syslog after you pass 74.0?

**Comment by gilesmartin** [comment]
/homebridge # tail -f /usr/lib/hisense/hisense.log
10.0.0.16 - - [05/May/2020 18:17:34] "GET /local_lan/commands.json HTTP/1.1" 200 -
10.0.0.16 - - [05/May/2020 18:17:34] "POST /local_lan/property/datapoint.json?cmd_id=268&status=200 HTTP/1.1" 200 -
10.0.0.16 - - [05/May/2020 18:17:34] "GET /local_lan/commands.json HTTP/1.1" 200 -
10.0.0.16 - - [05/May/2020 18:17:34] "POST /local_lan/property/datapoint.json?cmd_id=269&status=200 HTTP/1.1" 200 -
10.0.0.16 - - [05/May/2020 18:17:34] "GET /local_lan/commands.json HTTP/1.1" 200 -
10.0.0.16 - - [05/May/2020 18:17:34] "POST /local_lan/property/datapoint.json?cmd_id=270&status=200 HTTP/1.1" 200 -
10.0.0.16 - - [05/May/2020 18:17:34] "GET /local_lan/commands.json HTTP/1.1" 200 -
10.0.0.16 - - [05/May/2020 18:17:34] "POST /local_lan/property/datapoint.json?cmd_id=271&status=200 HTTP/1.1" 200 -
10.0.0.16 - - [05/May/2020 18:17:34] "GET /local_lan/commands.json HTTP/1.1" 200 -
10.0.0.16 - - [05/May/2020 18:17:34] "POST /local_lan/property/datapoint.json?cmd_id=272&status=200 HTTP/1.1" 200 -

**Comment by gilesmartin** [comment]
basically nothing being posted to the log

**Comment by deiger** [comment]
Hmm, that's strange. Added logging for incoming MQTT messages.

**Comment by ck007max** [comment]
Hello deiger, thank you for your reply. I have a question: is it possible that when home assistant receive the data from the server it is written in lower cases and it can't update the status? The only data that I can update is temperature, a number data. The other data (fan speed, modes and swing) can't be updated and changed, either.

**Comment by wifi75** [comment]
@deiger 
hopefully it will resolve soon....

**Comment by deiger** [comment]
The data sent to Home Assistant is in lower-case, as HA expects. This is handled [here](../blob/master/hisense.py#L695). Messages passed from HA are upper-cased, as the module expects ([here](../blob/master/hisense.py#L686)).
If you use my version of the configuration it should work properly.

**Comment by ck007max** [comment]
Ok, but if I understand right this is only for fan state. The problem is with all state of fan speed, modes and swing. If I use your config HA says null for that state. It seems that It can't read the right state, maybe because they have uppercase instead of lower case.

**Comment by deiger** [comment]
It isn't - specifically for fan, the state defined by HA (and cannot be changed) is fan_only, while Hisense use FAN. Everything else is just a matter of a case change.

**Comment by ashwinvandijk** [comment]
Would you like to share your Dockerfile with us?
