### ISSUE TITLE
Add app support to HiSense

### ISSUE THREAD

**Issue by refaelsommer** [deiger/AirCon#157]
Hi,
I use Homeassistant and the integration of HiSense
It works perfect with my room Aircons with tornado-us and thanks for that!!!

I would like if you can add “Universal WIFI” app name on the AppStore to the list of compatible aircons.
https://apps.apple.com/il/app/universal-wifi/id1529312961

is that possible?

Also if it is possible to add this app:
https://apps.apple.com/il/app/tornado-wifi-3/id1458091265

thanks,
Refael.S

**Comment by deiger** [comment]
I don't have visibility into Apple apps, but I checked the parallel Android apps, [Universal WIFI](https://play.google.com/store/apps/details?id=tornado.top.cn) and [Tornado WIFI 3](https://play.google.com/store/apps/details?id=com.tornado.tornadowifi3).
Unfortunately neither is Hisense-based, so the API wouldn't work. The former is really running code of Tuya, while the latter is running Broadlink code.
