### ISSUE TITLE
Australian FGLair split temperatures wrong

### ISSUE THREAD

**Issue by timh767** [deiger/AirCon#159]
I have an Australian Fujitsu wifi split a/c with FGLair.  

Running Home Assistant core-2022.4.7

This addon is mostly functional if I define fglair-us as the app code.  flgair-eu loaded but the only entity was "update status".

I have basic control of the a/c using the fglair-us setting, but it displays set temperature as -4 degrees C.  The a/c is actually set at 25 degrees C (according to the official FGLair phone app). Coincidence maybe but -4 C is 25 F.

/config/hisense/config_ac000w000768786.json info:

`"name": "AC000W000768786", "app": "fglair-us", "model": "AP-WA3E", "sw_version": "bc 2.6.17-fgl2 06/29/20 09:03:57 ID jre/mfg/2dfbf5d", "dsn": "AC000W000768786", "temp_type": "F" etc....`

I changed temp_type to "C" but no change to behaviour.

It would be great if this could be fixed, this is a popular brand AC in Australia.

**Comment by JonyCorp** [comment]
Same issue for my Hisense. 

I've tried moving to the EU app, but the a/c unit won't connect.

**Comment by AdamGit69** [comment]
I just installed this here in Oz and had exactly the same issue with my fujitsu split however it's working sweet now. Not sure why you have a different config file name however I also changed to US then all I did though was edit /config/hisense/config_fujitsudevice.json and changed to C as temp type. I restarted the addon and bam it works fine.. Not sure why your's isn't doing it!

**Comment by timh767** [comment]
Thanks for that feedback AdamGit69, good to know it does work on our units in Aus.  I'll keep working on it and try to figure out why mine isn't updating, will uninstall everything and start from scratch.

**Comment by timh767** [comment]
OK, uninstalled this add on, deleted the json file, restarted HA, reinstalled and configured and it's working now.  Temperature is displaying in C after I change the temp type in the json file.  Thanks!
