### ISSUE TITLE
Failed to save add-on configuration, Invalid list for option 'app' in HiSense Air Conditioners (c34eddb3_hisense_ac).

### ISSUE THREAD

**Issue by PJDamen** [deiger/AirCon#163]
I cannot figure what I'm doing wrong. I installed in Home Assistant through the add-on but I'm stuck on the configuration.

Any help would be appreciated.

<img width="1014" alt="hisense" src="https://user-images.githubusercontent.com/32208277/170993650-a7efaa95-38e9-4791-9396-d4ac4fff1255.png">

**Comment by deiger** [comment]
The `app:` prefix is redundant, it is already nested in it (see the field header). It should be just:
```yaml
- username: foo
  password: bar
  code: hisense-eu
```

**Comment by PJDamen** [comment]
Yes, that was it! Thanks a lot!
