### ISSUE TITLE
Aircon with FGlair cant select FAN Only mode 

### ISSUE THREAD

**Issue by pbvdven** [deiger/AirCon#168]
im using home assistant with the AirCon addon works great but the Fan only mode cant be selected or you can select it but wont switch to it.

**Comment by Zara-dev-meow** [comment]
+1

**Comment by tschut** [comment]
Having the same issue. Logging shows
```
I0806 08:58:44.776  mqtt_client.py:37] MQTT message Topic: hisense_ac/a0cc2beef7a1/operation_mode/command, Payload b'fan_only'
E0806 08:58:44.776  mqtt_client.py:56] Failed to parse value FAN_ONLY for property operation_mode
Traceback (most recent call last):
  File "/app/aircon/mqtt_client.py", line 53, in mqtt_on_message
    chosen_device.queue_command(prop_name, payload.upper())
  File "/app/aircon/aircon.py", line 159, in queue_command
    data_value = data_type[value]
  File "/usr/local/lib/python3.7/enum.py", line 357, in __getitem__
    return cls._member_map_[name]
KeyError: 'FAN_ONLY'
```

**Comment by tschut** [comment]
I'm thinking it might be due to this:
`  FAN = 5` in properties.py:128.

But I'm not sure, tried forking the repo and testing it but I haven't gotten my local HA yet to install the add-on from my forked repo.

**Comment by tschut** [comment]
Managed to reproduce it running locally. Opened #194 which fixes it for me.

**Comment by tschut** [comment]
It appears this issue is not fixed for me :( 
* If I select "fan only" in HA, it will switch back to the previous state a couple of seconds later
* If I set the A/C to "fan only" using the FGLair app, it is displayed correctly in HA

The logs when switching to "fan only"

> I0531 08:24:23.833  mqtt_client.py:37] MQTT message Topic: hisense_ac/a0cc2beef7a1/operation_mode/command, Payload b'fan_only'
> E0531 08:24:23.833  mqtt_client.py:55] Failed to parse value FAN_ONLY for property operation_mode
> Traceback (most recent call last):
>   File "/app/aircon/mqtt_client.py", line 53, in mqtt_on_message
>     chosen_device.queue_command(prop_name, payload.upper())
>   File "/app/aircon/aircon.py", line 159, in queue_command
>     data_value = data_type[value]
>   File "/usr/local/lib/python3.10/enum.py", line 440, in __getitem__
>     return cls._member_map_[name]
> KeyError: 'FAN_ONLY'
