### ISSUE TITLE
stuck in this log , can't find any fujitsu unit 

### ISSUE THREAD

**Issue by Zara-dev-meow** [deiger/AirCon#171]
log_level: INFO
mqtt_host: core-mosquitto
mqtt_user: xxxx
mqtt_pass: xxxxxx // declared separate user and password in mosquitto
port: 8888
app:
  - username:xx@xx.xx
    password: xxxxxxxxx
    code: fglair-eu

stuck in this log 

I0618 16:07:00.516  web_log.py:206] 192.168.1.103 [18/Jun/2022:14:07:00 +0000] "POST /local_lan/key_exchange.json HTTP/1.1" 200 213 "-" "-"
I0618 16:07:00.525  web_log.py:206] 192.168.1.101 [18/Jun/2022:14:07:00 +0000] "POST /local_lan/key_exchange.json HTTP/1.1" 200 213 "-" "-"
I0618 16:07:00.532  web_log.py:206] 192.168.1.103 [18/Jun/2022:14:07:00 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I0618 16:07:00.540  web_log.py:206] 192.168.1.101 [18/Jun/2022:14:07:00 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I0618 16:07:00.561  query_handlers.py:139] Decrypted: {"seq_no":0,"data":{"name":"operation_mode","value":0}}
I0618 16:07:00.569  web_log.py:206] 192.168.1.103 [18/Jun/2022:14:07:00 +0000] "POST /local_lan/property/datapoint.json?cmd_id=0&status=200 HTTP/1.1" 200 149 "-" "-"
I0618 16:07:00.572  query_handlers.py:139] Decrypted: {"seq_no":0,"data":{"name":"operation_mode","value":0}}
I0618 16:07:00.576  web_log.py:206] 192.168.1.101 [18/Jun/2022:14:07:00 +0000] "POST /local_lan/property/datapoint.json?cmd_id=0&status=200 HTTP/1.1" 200 149 "-" "-"
I0618 16:07:00.638  web_log.py:206] 192.168.1.101 [18/Jun/2022:14:07:00 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 461 "-" "-"
I0618 16:07:00.645  web_log.py:206] 192.168.1.103 [18/Jun/2022:14:07:00 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 461 "-" "-"
I0618 16:07:00.659  query_handlers.py:139] Decrypted: {"seq_no":1,"data":{"name":"fan_speed","value":0}}
I0618 16:07:00.664  web_log.py:206] 192.168.1.101 [18/Jun/2022:14:07:00 +0000] "POST /local_lan/property/datapoint.json?cmd_id=1&status=200 HTTP/1.1" 200 149 "-" "-"
I0618 16:07:00.669  query_handlers.py:139] Decrypted: {"seq_no":1,"data":{"name":"fan_speed","value":4}}
I0618 16:07:00.675  web_log.py:206] 192.168.1.103 [18/Jun/2022:14:07:00 +0000] "POST /local_lan/property/datapoint.json?cmd_id=1&status=200 HTTP/1.1" 200 149 "-" "-"
I0618 16:07:00.785  web_log.py:206] 192.168.1.101 [18/Jun/2022:14:07:00 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I0618 16:07:00.793  web_log.py:206] 192.168.1.103 [18/Jun/2022:14:07:00 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I0618 16:07:00.811  query_handlers.py:139] Decrypted: {"seq_no":2,"data":{"name":"adjust_temperature","value":250}}
I0618 16:07:00.815  web_log.py:206] 192.168.1.101 [18/Jun/2022:14:07:00 +0000] "POST /local_lan/property/datapoint.json?cmd_id=2&status=200 HTTP/1.1" 200 149 "-" "-"
I0618 16:07:00.821  query_handlers.py:139] Decrypted: {"seq_no":2,"data":{"name":"adjust_temperature","value":260}}
I0618 16:07:00.825  web_log.py:206] 192.168.1.103 [18/Jun/2022:14:07:00 +0000] "POST /local_lan/property/datapoint.json?cmd_id=2&status=200 HTTP/1.1" 200 149 "-" "-"
I0618 16:07:00.924  web_log.py:206] 192.168.1.101 [18/Jun/2022:14:07:00 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I0618 16:07:00.933  web_log.py:206] 192.168.1.103 [18/Jun/2022:14:07:00 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I0618 16:07:00.953  query_handlers.py:139] Decrypted: {"seq_no":3,"data":{"name":"af_vertical_direction","value":1}}
I0618 16:07:00.959  web_log.py:206] 192.168.1.101 [18/Jun/2022:14:07:00 +0000] "POST /local_lan/property/datapoint.json?cmd_id=3&status=200 HTTP/1.1" 200 149 "-" "-"
I0618 16:07:00.964  query_handlers.py:139] Decrypted: {"seq_no":3,"data":{"name":"af_vertical_direction","value":1}}
I0618 16:07:00.967  web_log.py:206] 192.168.1.103 [18/Jun/2022:14:07:00 +0000] "POST /local_lan/property/datapoint.json?cmd_id=3&status=200 HTTP/1.1" 200 149 "-" "-"
I0618 16:07:01.065  web_log.py:206] 192.168.1.101 [18/Jun/2022:14:07:01 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I0618 16:07:01.074  web_log.py:206] 192.168.1.103 [18/Jun/2022:14:07:01 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I0618 16:07:01.090  query_handlers.py:139] Decrypted: {"seq_no":4,"data":{"name":"af_vertical_swing","value":0}}
I0618 16:07:01.096  web_log.py:206] 192.168.1.101 [18/Jun/2022:14:07:01 +0000] "POST /local_lan/property/datapoint.json?cmd_id=4&status=200 HTTP/1.1" 200 149 "-" "-"
I0618 16:07:01.101  query_handlers.py:139] Decrypted: {"seq_no":4,"data":{"name":"af_vertical_swing","value":0}}
I0618 16:07:01.105  web_log.py:206] 192.168.1.103 [18/Jun/2022:14:07:01 +0000] "POST /local_lan/property/datapoint.json?cmd_id=4&status=200 HTTP/1.1" 200 149 "-" "-"
I0618 16:07:01.203  web_log.py:206] 192.168.1.101 [18/Jun/2022:14:07:01 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I0618 16:07:01.211  web_log.py:206] 192.168.1.103 [18/Jun/2022:14:07:01 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I0618 16:07:01.236  query_handlers.py:139] Decrypted: {"seq_no":5,"data":{"name":"af_horizontal_direction","value":0}}
I0618 16:07:01.242  web_log.py:206] 192.168.1.101 [18/Jun/2022:14:07:01 +0000] "POST /local_lan/property/datapoint.json?cmd_id=5&status=200 HTTP/1.1" 200 149 "-" "-"
I0618 16:07:01.246  query_handlers.py:139] Decrypted: {"seq_no":5,"data":{"name":"af_horizontal_direction","value":0}}
I0618 16:07:01.250  web_log.py:206] 192.168.1.103 [18/Jun/2022:14:07:01 +0000] "POST /local_lan/property/datapoint.json?cmd_id=5&status=200 HTTP/1.1" 200 149 "-" "-"
I0618 16:07:01.345  web_log.py:206] 192.168.1.101 [18/Jun/2022:14:07:01 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I0618 16:07:01.351  web_log.py:206] 192.168.1.103 [18/Jun/2022:14:07:01 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I0618 16:07:01.371  query_handlers.py:139] Decrypted: {"seq_no":6,"data":{"name":"af_horizontal_swing","value":0}}
I0618 16:07:01.376  web_log.py:206] 192.168.1.101 [18/Jun/2022:14:07:01 +0000] "POST /local_lan/property/datapoint.json?cmd_id=6&status=200 HTTP/1.1" 200 149 "-" "-"
I0618 16:07:01.380  query_handlers.py:139] Decrypted: {"seq_no":6,"data":{"name":"af_horizontal_swing","value":0}}
I0618 16:07:01.384  web_log.py:206] 192.168.1.103 [18/Jun/2022:14:07:01 +0000] "POST /local_lan/property/datapoint.json?cmd_id=6&status=200 HTTP/1.1" 200 149 "-" "-"
I0618 16:07:01.480  web_log.py:206] 192.168.1.101 [18/Jun/2022:14:07:01 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I0618 16:07:01.488  web_log.py:206] 192.168.1.103 [18/Jun/2022:14:07:01 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I0618 16:07:01.507  query_handlers.py:139] Decrypted: {"seq_no":7,"data":{"name":"economy_mode","value":0}}
I0618 16:07:01.511  web_log.py:206] 192.168.1.101 [18/Jun/2022:14:07:01 +0000] "POST /local_lan/property/datapoint.json?cmd_id=7&status=200 HTTP/1.1" 200 149 "-" "-"
I0618 16:07:01.515  query_handlers.py:139] Decrypted: {"seq_no":7,"data":{"name":"economy_mode","value":0}}
I0618 16:07:01.519  web_log.py:206] 192.168.1.103 [18/Jun/2022:14:07:01 +0000] "POST /local_lan/property/datapoint.json?cmd_id=7&status=200 HTTP/1.1" 200 149 "-" "-"
I0618 16:08:42.702  web_log.py:206] 192.168.1.101 [18/Jun/2022:14:08:42 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 269 "-" "-"
I0618 16:08:42.713  web_log.py:206] 192.168.1.103 [18/Jun/2022:14:08:42 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 269 "-" "-"

please give me help

**Comment by Zara-dev-meow** [comment]
i think is because mosquitto is not giving permission to access 

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] mosquitto.sh: executing... 
[17:36:33] INFO: SSL is not enabled
[cont-init.d] mosquitto.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[17:36:35] INFO: Starting NGINX for authentication handling...
[17:36:36] INFO: Starting mosquitto MQTT broker...
1655566596: Warning: Mosquitto should not be run as root/administrator.
[17:36:38] INFO: Successfully send discovery information to Home Assistant.
[17:36:39] INFO: Successfully send service information to the Supervisor.
1655566596: mosquitto version 2.0.11 starting
1655566596: Config loaded from /etc/mosquitto/mosquitto.conf.
1655566596: Loading plugin: /usr/share/mosquitto/go-auth.so
1655566596:  ├── Username/password checking enabled.
1655566596:  ├── TLS-PSK checking enabled.
1655566596:  └── Extended authentication not enabled.
1655566596: Opening ipv4 listen socket on port 1883.
1655566596: Opening ipv6 listen socket on port 1883.
1655566596: Opening websockets listen socket on port 1884.
1655566596: mosquitto version 2.0.11 running
1655566596: New connection from 127.0.0.1:36262 on port 1883.
1655566596: Client <unknown> closed its connection.
1655566597: New connection from 172.30.32.2:49054 on port 1883.
1655566597: Client <unknown> closed its connection.
1655566705: New connection from 172.30.32.1:49751 on port 1883.
1655566705: Client <unknown> disconnected, not authorised.
1655566717: New connection from 172.30.32.2:49056 on port 1883.
1655566717: Client <unknown> closed its connection.
1655566797: New connection from 172.30.32.1:43121 on port 1883.
1655566797: Client <unknown> disconnected, not authorised.
1655566827: New connection from 172.30.32.1:51739 on port 1883.
1655566827: Client <unknown> disconnected, not authorised.
1655566837: New connection from 172.30.32.2:49058 on port 1883.
1655566837: Client <unknown> closed its connection.
1655566947: New connection from 172.30.32.1:57457 on port 1883.
1655566947: Client <unknown> disconnected, not authorised.
1655566957: New connection from 172.30.32.2:49060 on port 1883.
1655566957: Client <unknown> closed its connection.
1655567067: New connection from 172.30.32.1:43935 on port 1883.
1655567067: Client <unknown> disconnected, not authorised.
1655567077: New connection from 172.30.32.2:49062 on port 1883.
1655567077: Client <unknown> closed its connection.
1655567189: New connection from 172.30.32.1:60045 on port 1883.
1655567189: Client <unknown> disconnected, not authorised.
1655567197: New connection from 172.30.32.2:49064 on port 1883.
1655567197: Client <unknown> closed its connection.
1655567309: New connection from 172.30.32.1:46915 on port 1883.
1655567309: Client <unknown> disconnected, not authorised.
1655567317: New connection from 172.30.32.2:49066 on port 1883.
1655567317: Client <unknown> closed its connection.
1655567429: New connection from 172.30.32.1:59665 on port 1883.
1655567429: Client <unknown> disconnected, not authorised.
1655567437: New connection from 172.30.32.2:49068 on port 1883.
1655567437: Client <unknown> closed its connection.
1655567550: New connection from 172.30.32.1:57265 on port 1883.
1655567550: Client <unknown> disconnected, not authorised.
1655567557: New connection from 172.30.32.2:49070 on port 1883.
1655567557: Client <unknown> closed its connection.
1655567670: New connection from 172.30.32.1:43843 on port 1883.
1655567670: Client <unknown> disconnected, not authorised.
1655567677: New connection from 172.30.32.2:49072 on port 1883.
1655567677: Client <unknown> closed its connection.
1655567790: New connection from 172.30.32.1:39975 on port 1883.
1655567790: Client <unknown> disconnected, not authorised.
1655567797: New connection from 172.30.32.2:49074 on port 1883.
1655567797: Client <unknown> closed its connection.
1655567912: New connection from 172.30.32.1:48003 on port 1883.
1655567912: Client <unknown> disconnected, not authorised.
1655567917: New connection from 172.30.32.2:49076 on port 1883.
1655567917: Client <unknown> closed its connection.
1655568032: New connection from 172.30.32.1:60837 on port 1883.
1655568032: Client <unknown> disconnected, not authorised.
1655568037: New connection from 172.30.32.2:49078 on port 1883.
1655568037: Client <unknown> closed its connection.
1655568088: New connection from 172.30.32.1:35591 on port 1883.
1655568088: Client <unknown> disconnected, not authorised.
1655568152: New connection from 172.30.32.1:36465 on port 1883.
1655568152: Client <unknown> disconnected, not authorised.
1655568157: New connection from 172.30.32.2:49080 on port 1883.



what can i do ?

**Comment by deiger** [comment]
The MQTT username and password should match those set in the MQTT integration:
![image](https://user-images.githubusercontent.com/45061021/174449702-0e9bfad5-cb3e-456e-b009-4cfb69456946.png)

**Comment by Zara-dev-meow** [comment]
<img width="374" alt="image" src="https://user-images.githubusercontent.com/20912128/174452586-506a0160-0337-49e3-a37c-075197859081.png">

already done that , after i used an yaml configuration of my 2 ac unit , now i have this

**Comment by deiger** [comment]
OK, what are you seeing in the log now?

**Comment by Zara-dev-meow** [comment]
aircon addon :

File "/app/aircon/query_handlers.py", line 73, in property_update_handler
    update = self._decrypt_and_validate(device, data)
  File "/app/aircon/query_handlers.py", line 143, in _decrypt_and_validate
    raise Error(f'Failed to decode message, {ex!r}:\n{text.decode("utf-8")}')
aircon.error.Error: Failed to decode message, JSONDecodeError("Expecting ',' delimiter: line 1 column 22 (char 21)"):
{"seq_no":0,"data":{}
I0619 13:20:37.287  web_log.py:206] 192.168.1.103 [19/Jun/2022:11:20:37 +0000] "POST /local_lan/property/datapoint.json?cmd_id=485&status=503 HTTP/1.1" 400 172 "-" "-"
I0619 13:20:37.385  web_log.py:206] 192.168.1.103 [19/Jun/2022:11:20:37 +0000] "POST /local_lan/key_exchange.json HTTP/1.1" 200 213 "-" "-"
I0619 13:20:37.400  web_log.py:206] 192.168.1.103 [19/Jun/2022:11:20:37 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I0619 13:20:38.456  query_handlers.py:139] Decrypted: {"seq_no":0,"data":{}
E0619 13:20:38.458  query_handlers.py:75] Failed to parse property.
Traceback (most recent call last):
  File "/app/aircon/query_handlers.py", line 141, in _decrypt_and_validate
    return json.loads(text.decode('utf-8'))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 22 (char 21)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/aircon/query_handlers.py", line 73, in property_update_handler
    update = self._decrypt_and_validate(device, data)
  File "/app/aircon/query_handlers.py", line 143, in _decrypt_and_validate
    raise Error(f'Failed to decode message, {ex!r}:\n{text.decode("utf-8")}')
aircon.error.Error: Failed to decode message, JSONDecodeError("Expecting ',' delimiter: line 1 column 22 (char 21)"):
{"seq_no":0,"data":{}
I0619 13:20:38.464  web_log.py:206] 192.168.1.103 [19/Jun/2022:11:20:38 +0000] "POST /local_lan/property/datapoint.json?cmd_id=486&status=503 HTTP/1.1" 400 172 "-" "-"
I0619 13:20:38.503  web_log.py:206] 192.168.1.103 [19/Jun/2022:11:20:38 +0000] "POST /local_lan/key_exchange.json HTTP/1.1" 200 213 "-" "-"
I0619 13:20:38.519  web_log.py:206] 192.168.1.103 [19/Jun/2022:11:20:38 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 481 "-" "-"
I0619 13:20:39.037  query_handlers.py:139] Decrypted: {"seq_no":0,"data":{}
E0619 13:20:39.038  query_handlers.py:75] Failed to parse property.
Traceback (most recent call last):
  File "/app/aircon/query_handlers.py", line 141, in _decrypt_and_validate
    return json.loads(text.decode('utf-8'))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 22 (char 21)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/aircon/query_handlers.py", line 73, in property_update_handler
    update = self._decrypt_and_validate(device, data)
  File "/app/aircon/query_handlers.py", line 143, in _decrypt_and_validate
    raise Error(f'Failed to decode message, {ex!r}:\n{text.decode("utf-8")}')
aircon.error.Error: Failed to decode message, JSONDecodeError("Expecting ',' delimiter: line 1 column 22 (char 21)"):
{"seq_no":0,"data":{}
I0619 13:20:39.043  web_log.py:206] 192.168.1.103 [19/Jun/2022:11:20:39 +0000] "POST /local_lan/property/datapoint.json?cmd_id=487&status=503 HTTP/1.1" 400 172 "-" "-"
I0619 13:20:49.506  web_log.py:206] 192.168.1.103 [19/Jun/2022:11:20:49 +0000] "POST /local_lan/key_exchange.json HTTP/1.1" 200 213 "-" "-"
I0619 13:20:49.522  web_log.py:206] 192.168.1.103 [19/Jun/2022:11:20:49 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 269 "-" "-"
I0619 13:21:03.507  query_handlers.py:139] Decrypted: {"seq_no":287,"data":{"name":"adjust_temperature","value":230}}
I0619 13:21:03.510  web_log.py:206] 192.168.1.101 [19/Jun/2022:11:21:03 +0000] "POST /local_lan/property/datapoint.json HTTP/1.1" 200 149 "-" "-"
I0619 13:21:12.644  query_handlers.py:139] Decrypted: {"seq_no":288,"data":{"name":"adjust_temperature","value":230}}
I0619 13:21:12.648  web_log.py:206] 192.168.1.101 [19/Jun/2022:11:21:12 +0000] "POST /local_lan/property/datapoint.json HTTP/1.1" 200 149 "-" "-"
I0619 13:21:43.025  query_handlers.py:139] Decrypted: {"seq_no":289,"data":{"name":"adjust_temperature","value":230}}
I0619 13:21:43.030  web_log.py:206] 192.168.1.101 [19/Jun/2022:11:21:43 +0000] "POST /local_lan/property/datapoint.json HTTP/1.1" 200 149 "-" "-"
I0619 13:21:53.584  query_handlers.py:139] Decrypted: {"seq_no":290,"data":{"name":"adjust_temperature","value":230}}
I0619 13:21:53.589  web_log.py:206] 192.168.1.101 [19/Jun/2022:11:21:53 +0000] "POST /local_lan/property/datapoint.json HTTP/1.1" 200 149 "-" "-"
I0619 13:22:23.455  query_handlers.py:139] Decrypted: {"seq_no":291,"data":{"name":"adjust_temperature","value":230}}
I0619 13:22:23.459  web_log.py:206] 192.168.1.101 [19/Jun/2022:11:22:23 +0000] "POST /local_lan/property/datapoint.json HTTP/1.1" 200 149 "-" "-"
I0619 13:22:33.653  query_handlers.py:139] Decrypted: {"seq_no":292,"data":{"name":"adjust_temperature","value":230}}
I0619 13:22:33.658  web_log.py:206] 192.168.1.101 [19/Jun/2022:11:22:33 +0000] "POST /local_lan/property/datapoint.json HTTP/1.1" 200 149 "-" "-"
I0619 13:22:33.841  web_log.py:206] 192.168.1.103 [19/Jun/2022:11:22:33 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 269 "-" "-"
I0619 13:23:04.046  query_handlers.py:139] Decrypted: {"seq_no":293,"data":{"name":"adjust_temperature","value":230}}
I0619 13:23:04.051  web_log.py:206] 192.168.1.101 [19/Jun/2022:11:23:04 +0000] "POST /local_lan/property/datapoint.json HTTP/1.1" 200 149 "-" "-"
I0619 13:23:14.716  query_handlers.py:139] Decrypted: {"seq_no":294,"data":{"name":"adjust_temperature","value":230}}
I0619 13:23:14.721  web_log.py:206] 192.168.1.101 [19/Jun/2022:11:23:14 +0000] "POST /local_lan/property/datapoint.json HTTP/1.1" 200 149 "-" "-"
I0619 13:23:44.524  query_handlers.py:139] Decrypted: {"seq_no":295,"data":{"name":"adjust_temperature","value":230}}
I0619 13:23:44.529  web_log.py:206] 192.168.1.101 [19/Jun/2022:11:23:44 +0000] "POST /local_lan/property/datapoint.json HTTP/1.1" 200 149 "-" "-"
I0619 13:23:54.778  query_handlers.py:139] Decrypted: {"seq_no":296,"data":{"name":"adjust_temperature","value":230}}
I0619 13:23:54.784  web_log.py:206] 192.168.1.101 [19/Jun/2022:11:23:54 +0000] "POST /local_lan/property/datapoint.json HTTP/1.1" 200 149 "-" "-"
I0619 13:24:17.975  web_log.py:206] 192.168.1.103 [19/Jun/2022:11:24:17 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 269 "-" "-"
I0619 13:24:25.832  query_handlers.py:139] Decrypted: {"seq_no":297,"data":{"name":"adjust_temperature","value":230}}
I0619 13:24:25.837  web_log.py:206] 192.168.1.101 [19/Jun/2022:11:24:25 +0000] "POST /local_lan/property/datapoint.json HTTP/1.1" 200 149 "-" "-"
I0619 13:24:35.249  query_handlers.py:139] Decrypted: {"seq_no":298,"data":{"name":"adjust_temperature","value":230}}
I0619 13:24:35.255  web_log.py:206] 192.168.1.101 [19/Jun/2022:11:24:35 +0000] "POST /local_lan/property/datapoint.json HTTP/1.1" 200 149 "-" "-"
I0619 13:25:05.783  query_handlers.py:139] Decrypted: {"seq_no":299,"data":{"name":"adjust_temperature","value":230}}
I0619 13:25:05.789  web_log.py:206] 192.168.1.101 [19/Jun/2022:11:25:05 +0000] "POST /local_lan/property/datapoint.json HTTP/1.1" 200 149 "-" "-"
I0619 13:25:15.928  query_handlers.py:139] Decrypted: {"seq_no":300,"data":{"name":"adjust_temperature","value":230}}
I0619 13:25:15.934  web_log.py:206] 192.168.1.101 [19/Jun/2022:11:25:15 +0000] "POST /local_lan/property/datapoint.json HTTP/1.1" 200 149 "-" "-"
I0619 13:25:46.511  query_handlers.py:139] Decrypted: {"seq_no":301,"data":{"name":"adjust_temperature","value":230}}
I0619 13:25:46.516  web_log.py:206] 192.168.1.101 [19/Jun/2022:11:25:46 +0000] "POST /local_lan/property/datapoint.json HTTP/1.1" 200 149 "-" "-"
I0619 13:25:56.983  query_handlers.py:139] Decrypted: {"seq_no":302,"data":{"name":"adjust_temperature","value":230}}
I0619 13:25:56.987  web_log.py:206] 192.168.1.101 [19/Jun/2022:11:25:56 +0000] "POST /local_lan/property/datapoint.json HTTP/1.1" 200 149 "-" "-"
I0619 13:26:04.138  web_log.py:206] 192.168.1.103 [19/Jun/2022:11:26:04 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 269 "-" "-"
I0619 13:26:28.033  query_handlers.py:139] Decrypted: {"seq_no":303,"data":{"name":"adjust_temperature","value":230}}
I0619 13:26:28.037  web_log.py:206] 192.168.1.101 [19/Jun/2022:11:26:28 +0000] "POST /local_lan/property/datapoint.json HTTP/1.1" 200 149 "-" "-"
I0619 13:26:37.178  query_handlers.py:139] Decrypted: {"seq_no":304,"data":{"name":"adjust_temperature","value":230}}
I0619 13:26:37.183  web_log.py:206] 192.168.1.101 [19/Jun/2022:11:26:37 +0000] "POST /local_lan/property/datapoint.json HTTP/1.1" 200 149 "-" "-"
I0619 13:27:07.733  query_handlers.py:139] Decrypted: {"seq_no":305,"data":{"name":"adjust_temperature","value":230}}
I0619 13:27:07.737  web_log.py:206] 192.168.1.101 [19/Jun/2022:11:27:07 +0000] "POST /local_lan/property/datapoint.json HTTP/1.1" 200 149 "-" "-"

**Comment by Zara-dev-meow** [comment]
@deiger 
As you can see mqtt explorer is seeing correcly the ACs 
<img width="292" alt="image" src="https://user-images.githubusercontent.com/20912128/174672683-afc2261f-9c33-4746-8a0e-6e66baecf3d0.png">

**Comment by script0rwins** [comment]
Hy,

here are just my 2 cents:

remove hisense_ac plugin.
*Start an MQTT Broker without user and pass protection,
*Remove config/hisense_ac folder from your homeassistant installation
*Install hisense addon to Homeasstistant,
*Config Plugin:
host: mqtthost,
user: mycoolusername (even if no user+pass is set)
pass: mycoolpassword (even if no user+pass is set)
port: 8888 <= This is NOT the MQTT Port. This is where the ACs are connecting
*add advanced config like 
app:
username:xx@xx.xx <==== WITHOUT (mailto:xx@xx.xx) and [].. only MAIL!
password: xxxxxxxxx
code: fglair-eu

* Start up plugin,
* be sure that the mqtt broker is added to homeassistant
* homeassistant should automatically find the entities.
* Check Log of hinsence_ac

Hope this helps,
Chris

**Comment by Zara-dev-meow** [comment]
hi now i have all my acs in my dashboard , yesterday they were all operative , now one is giving me no control from HA but can retrieve the status 
<img width="241" alt="image" src="https://user-images.githubusercontent.com/20912128/174822645-e3c45046-d68c-4a0b-a12d-f3eb1afbaee0.png">

it says just this when i send the command 
I0621 16:20:08.692  mqtt_client.py:37] MQTT message Topic: hisense_ac/b8d7af40480f/operation_mode/command, Payload b'off'

**Comment by Zara-dev-meow** [comment]
closing this to open another about the last comment
