### ISSUE TITLE
Device unavailable.

### ISSUE THREAD

**Issue by Raz0rX** [deiger/AirCon#176]
Hello,

I followed the instructions and installed the integration via Home Assistant Supervisor with MQTT broker.
The entity is show but it shows that it is unavailable (shows became unavailable message every 2-3 seconds).

I get this on the logs. 

<img width="1029" alt="Screenshot 2022-06-25 at 3 08 15 PM" src="https://user-images.githubusercontent.com/4748130/175772868-cad63bfa-ff57-4c68-ac31-d92dc14cf32b.png">

Any ideas?

**Comment by deiger** [comment]
`1883` is the port used for MQTT, you should use a different port for the server. See #106.

**Comment by Raz0rX** [comment]
@deiger It is now set to 8888 and worked. Thank you!

**Comment by deiger** [comment]
Sure thing!
