### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by kevtuning** [deiger/AirCon#208]
Hi,

I use a FGLair system.

This morning I receive this message... every x seconds...
E1130 08:39:06.662  notifier.py:121] Failed to connect to 192.168.1.246, maybe it is offline?

The system is reachable from the FGLair app...

I restarded the HVAC itself, the add-on etc... 

1st question: from where is coming this IP 192.168.1.246 ? Is it supposed to be the IP from the HVAC ? 
2nd : Is the add-on requesting/sending data to the FGLair api or locally ?

**Comment by vyruz1986** [comment]
The 192.168.1.246 will indeeed be your device's IP address.
This addon does not use the FGLair API. It starts by sending a request (`<device ip>/local_reg.json`) to the device, telling it to start polling this addons service over the local network. The device should then start polling this addong, posting status updates ,and collecting configuration changes (e.g. set temperature change).

**Comment by kevtuning** [comment]
Thanks @vyruz1986 for the explanantion !

My router got an update this night... and the device had change of IP... and I found the solution here: https://github.com/deiger/AirCon/issues/131

I made an IP reservation now....
