### ISSUE TITLE
Can't change mode of device

### ISSUE THREAD

**Issue by JacekJI** [deiger/AirCon#215]
Integration works but I only turn on/off and change temperature 

It's impossible to change mode of device.

Foe example heating--->cooling ect

![Screenshot_20230129_202346_Home Assistant](https://user-images.githubusercontent.com/120251550/215591693-adf84e39-5584-4dea-9b58-5ced4329fc7e.jpg)

**Comment by Sagadiniz** [comment]
Same! If you manage to solve it please tell!

**Comment by dab-17** [comment]
same problem

**Comment by PaperellaVerde** [comment]
Same my side, I just worked out how to "bypass" this issue manually. I noticed that the device start in the latest used "mode". Therefore, when I move from winter to summer and vice-versa I'm just going through the devices with the remote, to power it on on the desired mode, then it works for the rest of the season with the automation.  
maybe that help/work for you ;)

**Comment by JacekJI** [comment]
Yes, after yesterday update addon it's working fine 😉

**Comment by Sagadiniz** [comment]
Same here, yesterday's update solved it. Thanks

**Comment by JacekJI** [comment]
Update of addon solved problem!
