### ISSUE TITLE
attribute name must be string

### ISSUE THREAD

**Issue by schiettf** [deiger/AirCon#216]
Hi,
Thank you very much guys for developing this solution, which allows HA to stop my heat pump during "critical peak hours", when rates increase x5! In my setup, the FGLair app, Google Home or HA (using your AirCon add-on) communicate with the heat pump through a UTY-TFNXZ2 Wifi module. 

However, for the last week or so, the AirCon add-on crashes on start up, complaining that an attribute name must be string in /app/aircon/aircon.py, line 109, in get_property.  The log is attached.

I have AirCon 0.3.10. I'm running HA core_2023.2.2. I tried reverting back to core_2023.1.7 but no luck. Mosquitto broker 6.1.3 didn't update lately from what I can see, so I would be surprised this is the issue. Not sure if it's related, but at about the same time, Google Home could no longer communicate with the heat pump either. I had to "forget" the device and re-install it. I also remember having trouble with the FGLair app some time ago. So it might be a change on Fujitsu side.

[AirConCrashLog.log](https://github.com/deiger/AirCon/files/10716966/AirConCrashLog.log)

**Comment by schiettf** [comment]
The problem apparently disappeared after HA core_2023.3 update. Maybe related.

**Comment by indiealexh** [comment]
I am having this issue now. I'll create a new ticket if I can't find a solution and post here with a solution if I find one.
