### ISSUE TITLE
Docker compose not completing

### ISSUE THREAD

**Issue by tdigu** [deiger/AirCon#223]
I get the following error trying to set up a docker compose container:
This is when running the command docker-compose up -d in the same directory as options.json and docker-compose.yaml
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    import aircon
ModuleNotFoundError: No module named 'aircon'
ERROR: Service 'copy_config' failed to build: The command '/bin/sh -c python setup.py install' returned a non-zero code: 1

**Comment by soydeleon** [comment]
I have the same problem

#  docker-compose up
Building copy_config
[+] Building 0.1s (2/2) FINISHED
 => [internal] load .dockerignore                                                                                                     0.0s
 => => transferring context: 2B                                                                                                       0.0s
 => [internal] load build definition from Dockerfile                                                                                  0.0s
 => => transferring dockerfile: 2B                                                                                                    0.0s
ERROR: failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount1628610394/Dockerfile: no such file or directory
ERROR: Service 'copy_config' failed to build : Build failed

**Comment by soydeleon** [comment]
I workarround this with new docker  docker-compose.yaml
version: '3'
services:
  hisense_ac:
    image: deiger/aircon:0.3.14
    container_name: hisense_ac
    healthcheck:
      disable: true
    environment:
      - CONFIG_DIR=/config
      - OPTIONS_FILE=/config/options.json
    network_mode: host
    volumes:
      - /opt/hisense:/config

and then, copy the options.json to the /docker/hisense directory

**Comment by bigdogevan** [comment]
I just got this installed last night, had the same errors but overcame them. I found the instructions very vague. I used /opt/hisense for the install and my docker compose is located at /opt. All the required files are listed here (https://github.com/deiger/AirCon). The instructions say that you only need the docker compose and options file, but you need more. I had to copy the Dockerfile, README.md, run.sh, setup.py files and the folder "aircon" to my /opt directory. my options.json is in /opt/hisense

**Comment by tdigu** [comment]
In case someone else finds this, i found bigdogevan's instructions to work as well as soydelon's work around.
