### ISSUE TITLE
FGLair temperature on 0.3.14 (2023-03-28)

### ISSUE THREAD

**Issue by kevtuning** [deiger/AirCon#227]
Hi, 

I have updated to version 0.3.14 (2023-03-28)  in order to get FGLair current temperature.

Do I have have something specific after update ? (I've restarted HA and the add-on...)

Tx !

**Comment by kevtuning** [comment]
What I find in the logs:

`E0508 12:44:42.742  query_handlers.py:75] Failed to parse property.
Traceback (most recent call last):
  File "/app/aircon/query_handlers.py", line 141, in _decrypt_and_validate
    return json.loads(text.decode('utf-8'))
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 23 (char 22)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/aircon/query_handlers.py", line 73, in property_update_handler
    update = self._decrypt_and_validate(device, data)
  File "/app/aircon/query_handlers.py", line 143, in _decrypt_and_validate
    raise Error(f'Failed to decode message, {ex!r}:\n{text.decode("utf-8")}')
aircon.error.Error: Failed to decode message, JSONDecodeError("Expecting ',' delimiter: line 1 column 23 (char 22)"):
{"seq_no":10,"data":{}`

**Comment by kevtuning** [comment]
Oh... we don't have the same thing...

I have no display_temperature message...
![image](https://user-images.githubusercontent.com/5998776/237031897-f5941883-9da1-4eef-8334-6856e89ee497.png)

**Comment by gyro-labs** [comment]
There is no temperature in 0.3.14 yet. I implemented it in #224 , waiting for approval from the dev.

**Comment by kevtuning** [comment]
Thanks @gyro-labs  I should misunderstand the changelog:
![image](https://github.com/deiger/AirCon/assets/5998776/ecff2e1d-0ead-4aee-834a-ece7dad5df81)
![image](https://github.com/deiger/AirCon/assets/5998776/21d12cae-82a2-4b92-bb37-9fbdb93d58a7)

**Comment by kevtuning** [comment]
If it was not planned to be in this release... there's no sense to keep this issue open... I close it
