### ISSUE TITLE
Help .... it doesn't work after HA 2023.8 update !!!

### ISSUE THREAD

**Issue by zlucio** [deiger/AirCon#248]
After the update of HA 2023.8 the entities are no longer recognized and are not available. The names have been changed to MQTT !!!
"Some MQTT entities have an entity name starting with the device name. This is not expected. To avoid a duplicate name, the device name prefix is ​​stripped of the entity name as a workaround. Please inform the software application maintainer providing affected entities to resolve this issue."
HELP
TNX

**Comment by deiger** [comment]
Home Assistant should offer to install the update in the Add-ons page.

**Comment by deiger** [comment]
My guess is that the repository does not exist on your add-on store. Please try re-adding it.
