### ISSUE TITLE
Stopped working with fgl since updating from 3.13

### ISSUE THREAD

**Issue by PatrikNorrgard** [deiger/AirCon#251]
Hi,

I updated the HA Addon from 03.13 to the latest 03.15 and both my Fujitsu AC:s became unavailable.
The log has a bunch of entries saying cannot connect to 10.0.0.31 and 10.0.0.150 (which are the correct IP:s). Both are online and controllable via the FGL Air app.

My entities are showing this:
"This entity is no longer being provided by the mqtt integration. If the entity is no longer in use, delete it in settings."

These are the devices as shown under the MQTT integration:
![image](https://github.com/deiger/AirCon/assets/1492787/45de61f4-a14a-4952-a77c-46c4b608803e)

Addon config:

log_level: WARNING
mqtt_host: core-mosquitto
mqtt_user: MqttUser
mqtt_pass: mqtt
port: 8006
app:
  - username: REDACTED
    password: REDACTED
    code: fglair-eu

Tried uninstalling + reinstalling and now log shows nothing.

**Comment by essegi65** [comment]
similar problem with hisense air conditioner it returns this MQTT error:

Logger: homeassistant.components.mqtt.mixins
Source: components/mqtt/mixins.py:292
Integration: MQTT ([documentation](https://www.home-assistant.io/integrations/mqtt), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+mqtt%22))
First occurred: 12:35:30 (1 occurrences)
Last logged: 12:35:30

Error 'string value is None for dictionary value @ data['name']' when processing MQTT discovery message topic: 'homeassistant/climate/ca2c4facae90/hvac/config', message: '{'name': None, 'unique_id': 'ca2c4facae90', 'device': {'identifiers': ['hisense_ac_ca2c4facae90'], 'manufacturer': 'Hisense (hisense-eu)', 'model': 'Smart-1-70-eu', 'name': 'condisalotto', 'sw_version': 'ADA 1.4.3-beta ameba 2018-03-28 19:20:06 8f40fe89d'}, 'availability': [{'topic': 'hisense_ac/LWT'}, {'topic': 'hisense_ac/ca2c4facae90/available/status'}], 'precision': 1.0, 'temperature_unit': 'C', 'current_temperature_topic': 'hisense_ac/ca2c4facae90/f_temp_in/status', 'fan_mode_command_topic': 'hisense_ac/ca2c4facae90/t_fan_speed/command', 'fan_mode_state_topic': 'hisense_ac/ca2c4facae90/t_fan_speed/status', 'fan_modes': ['auto', 'lower', 'low', 'medium', 'high', 'higher'], 'mode_command_topic': 'hisense_ac/ca2c4facae90/t_work_mode/command', 'mode_state_topic': 'hisense_ac/ca2c4facae90/t_work_mode/status', 'modes': ['off', 'fan_only', 'heat', 'cool', 'dry', 'auto'], 'swing_mode_command_topic': 'hisense_ac/ca2c4facae90/t_fan_power/command', 'swing_mode_state_topic': 'hisense_ac/ca2c4facae90/t_fan_power/status', 'swing_modes': ['on', 'off'], 'temperature_command_topic': 'hisense_ac/ca2c4facae90/t_temp/command', 'temperature_state_topic': 'hisense_ac/ca2c4facae90/t_temp/status', 'max_temp': '30', 'min_temp': '16', 'platform': 'mqtt'}'

**Comment by RealLord** [comment]
**similar problem with hisense air conditioner it returns this autodiscovery MQTT error:**
`Error 'string value is None for dictionary value @ data['name']' when processing MQTT discovery message topic: 'homeassistant/climate/ca2c4f958e59/hvac/config', message: '{'name': None, 'unique_id': 'ca2c4f958e59', 'device': {'identifiers': ['hisense_ac_ca2c4f958e59'], 'manufacturer': 'Hisense (hisense-eu)', 'model': 'Smart-1-110-eu', 'name': 'Кондиционер 2', 'sw_version': 'ADA 1.4.3-beta ameba 2018-03-28 19:20:06 8f40fe89d'}, 'availability': [{'topic': 'hisense_ac/LWT'}, {'topic': 'hisense_ac/ca2c4f958e59/available/status'}], 'precision': 1.0, 'temperature_unit': 'C', 'current_temperature_topic': 'hisense_ac/ca2c4f958e59/f_temp_in/status', 'fan_mode_command_topic': 'hisense_ac/ca2c4f958e59/t_fan_speed/command', 'fan_mode_state_topic': 'hisense_ac/ca2c4f958e59/t_fan_speed/status', 'fan_modes': ['auto', 'lower', 'low', 'medium', 'high', 'higher'], 'mode_command_topic': 'hisense_ac/ca2c4f958e59/t_work_mode/command', 'mode_state_topic': 'hisense_ac/ca2c4f958e59/t_work_mode/status', 'modes': ['off', 'fan_only', 'heat', 'cool', 'dry', 'auto'], 'swing_mode_command_topic': 'hisense_ac/ca2c4f958e59/t_fan_power/command', 'swing_mode_state_topic': 'hisense_ac/ca2c4f958e59/t_fan_power/status', 'swing_modes': ['on', 'off'], 'temperature_command_topic': 'hisense_ac/ca2c4f958e59/t_temp/command', 'temperature_state_topic': 'hisense_ac/ca2c4f958e59/t_temp/status', 'max_temp': '30', 'min_temp': '16', 'platform': 'mqtt'}'`

**Comment by deiger** [comment]
This was changed in order to conform with HA 2023.8, per [this](https://developers.home-assistant.io/blog/2023-057-21-change-naming-mqtt-entities/).
Are you using the latest version of HA?
I've tried removing the entity name altogether, version 0.3.16. Please see if that helps.

**Comment by PatrikNorrgard** [comment]
Hi, 0.3.16 version fixed the issue. I was on 2023.7.3, I don't dare to jump on the first release of the month.

Thank you!

**Comment by deiger** [comment]
Cool, thanks for letting me know.
