### ISSUE TITLE
Latest update

### ISSUE THREAD

**Issue by GZ-3** [deiger/AirCon#252]
When trying to update from home assistant this error comes up:

Can't install deiger/aircon:0.3.17: 404 Client Error for http+docker://localhost/v1.43/images/create?tag=0.3.17&fromImage=deiger%2Faircon&platform=linux%2Famd64: Not Found ("manifest for deiger/aircon:0.3.17 not found: manifest unknown: manifest unknown")

**Comment by zlucio** [comment]
I can't update the integration so I uninstalled and reinstalled everything. But I have this error.....!!! Thanks for your help
![2023-08-07 11 09 37](https://github.com/deiger/AirCon/assets/63413581/ad5e43da-daf0-44ea-95b8-52dccbdb945f)

**Comment by GZ-3** [comment]
I uninstalled the integration and now I can't install it again, same error as in the first post.

**Comment by deiger** [comment]
The update to docker hub was stalled. Please try now.

**Comment by dragorex71** [comment]
I had the same problem, now fixed.
Thanks

**Comment by GZ-3** [comment]
Thanks!
