### ISSUE TITLE
Breaks after Updating to Homeassistant Core version 2023.8.0

### ISSUE THREAD

**Issue by refaelOW** [deiger/AirCon#254]
There are breaking changes to MQTT in 2023.8.0 version and since then my climate Air-conditioners do not work, they are unavailable.

Please fix asap 🙏🏻🙏🏻🙏🏻

**Comment by kevtuning** [comment]
Hi,

Everything is working fine on my side with 2023.8.0 and 2023.8.1 and the latest version of the add-on...

**Comment by refaelOW** [comment]
I have 6 Tornado air conditioners and they become unavailable when updating
to 2023.8.0
How can I find what’s the issue?

**Comment by refaelOW** [comment]
I have version 0.3.10 what is the latest version?

**Comment by refaelOW** [comment]
I have added the repository link to the addons in homeassistant and now
updating to 0.3.17 then I will test it with core 2023.8.1 and will let you
know.

Thanks for the help 🙏🏻

**Comment by refaelOW** [comment]
After updating to version 0.3.10 to 0.3.17 all works now 😆

Thanks, I didn’t realize that I was on an old version
