### ISSUE TITLE
Issues configuring Fujitsu General aircon units

### ISSUE THREAD

**Issue by ceemjay** [deiger/AirCon#259]
Please can someone advise as to how to get this working please?

Using Home Assistant 2023.10.5 on RPi.  Most things are working fine including a device that usess MQTT (though I haven't really managed to get my head around MQTT yet)

My YAML is this:
mqtt_host: 192.168.1.140
mqtt_port: 1883
mqtt_user: mqttuser
mqtt_pass: *******
port: 8877
app:
  - username: ********
    password: ********
    code: fglair-eu

The username and password are the ones used on the FGLair android app.
The MQTT credentials work with MQTT Explorer
I have tried a few different port numbers (it is not clear to me what this port is used for)

The only error in the log is this:
E1102 09:23:30.166  discovery.py:71] No device is configured! Please configure a device first.

I cant see how to configure a device nor where any of the aircon add-on code is stored - neither File editor add-on nor going to Terminal shell and using the find command. 

I still consider myself a HA novice as far as its internals go but fairly OK witht the UI/front end.

Thanks

**Comment by vyruz1986** [comment]
Do you see the indoor units in your android app with the same credentials?

**Comment by ceemjay** [comment]
The Android app was fine but I couldn't find a way to display the password to check. It took over 30 mins to finally reset the password on the FG website and I am hignly embarrassed to say that my password manager had the incorrect password! 

In my defence I would have expected an authentication error message rather than device not found.

We got there in the end - thank you for the prompt and sorry for my stupidity!
