### ISSUE TITLE
FGLair device not discovered

### ISSUE THREAD

**Issue by constantin-baciu** [deiger/AirCon#262]
Hi all,

I've been using this as a home assistant add-on for a while.
I used to have 1 Fujitsu ac, and that is discovered by the add-on.
But, I've added another Fujitsu add-on to my FGLair account, same location, but on a different network. Well, the second ac is not discovered by the addon.

Could this be because it's on a different network? The ac shows up fine in the FGLair app (same account)

Thanks!

**Comment by cvhoutvi** [comment]
Hello,
As far as I know this Add-On, it must be in the same network as the FGLair ac. It seems a security protection of the Fujitsu ac that it can only talk with a local controller whiting its own network space.

**Comment by deiger** [comment]
Indeed, the add-on interacts with the AC locally, rather than through the cloud, as it is far better WRT reliability and security - after setup, you can prevent the AC from accessing the Internet. So if an AC is in a different network, naturally that won't work.
