### ISSUE TITLE
Is prerequisite #4 (internet access blocking) mandatory or optional?

### ISSUE THREAD

**Issue by GED8006** [deiger/AirCon#272]
Hi,

A prerequisite is normally a mandatory task. However, point 4 which refers to internet blocking seems to be optional. Is it possible to make the instruction more specific or remove it from the prerequisites? What is the purpose of this instruction?

Personally, my router does not allow blocking Internet access (no mac filtering, no firewall). I then ask myself the question if I have to find another way to block Internet access which will require a lot of effort or if the prerequisite is only a suggestion given that Internet access through my A/C will no longer be necessary. What are the risks if I don't block Internet access? Can Fujitsu's cloud server and my personal server coexist?

Here is the prerequisite:

Once everything has been configured, the A/Cs **can be blocked** from connecting to the internet, as it will no longer be needed. Set them static IP addresses in the router, and write them down.

Note: To avoid the need for manual changes later, make sure the app is aware of the new IP addresses before disconnecting the A/Cs from the internet.

Thanks for clarifying the point

**Comment by deiger** [comment]
Blocking Internet access is not mandatory.
It is good hygiene, considering that the control of the A/C by the addon is done locally, so there is no reason to expose your network. Theoretically, a firmware update may change the LAN token, or even disable the LAN access altogether. But I have not seen that happening so far.
