### ISSUE TITLE
Problem with configuration

### ISSUE THREAD

**Issue by PeterH63** [deiger/AirCon#296]
I try to get the Aircon-Add-On running in my homeassistant. My configuration looks like this.

log_level: INFO
mqtt_host: core-mosquitto
mqtt_port: 1883
mqtt_user: mqtt-user
mqtt_pass: mqtt
port: 8123
app:
  -username: xxxxxxxxxxxx@xxx.com
  password: xxxxxxxxxxxx
  code: oem-eu

The error-message looks like this

Fehler beim Speichern der Add-on Konfiguration, Invalid list for option 'app' in HiSense Air Conditioners (c34eddb3_hisense_ac). Got {'log_level': 'INFO', 'mqtt_host': 'core-mosquitto', 'mqtt_port': 1883, 'mqtt_user': 'mqtt-user', 'mqtt_pass': 'mqtt', 'port': 8123, 'app': {'-username': xxxxxxxxxxxx@xxx.com, '-password': xxxxxxxxxxxx, '-code': 'oem-eu'}}

**Comment by freaktrio** [comment]
looks like it needs top be indented, take example from my configuration:
log_level: INFO
mqtt_host: core-mosquitto
mqtt_port: 1883
mqtt_user: user
mqtt_pass: pass
port: 1888
app:
  - username: email
    password: password
    code: tornado-us

**Comment by PeterH63** [comment]
Thank you for your help. I got it running
