### ISSUE TITLE
Login Server error

### ISSUE THREAD

**Issue by scaramatto** [deiger/AirCon#3]
i try, with this code:
./query_cli.py --user mymail@mail.com --passwd Mypass --app oem-eu --config config.json
(Same credential of my app: "HI-Smart AC")
but i view this error:
query_cli.py:112] Failed to login to Hisense server: <http.client.HTTPResponse object at 0x0000025A7720DAC8>
some advice?

**Comment by deiger** [comment]
The login has failed.
Could you try downloading the script again and re-running it? I've updated the error message to be clearer.

**Comment by scaramatto** [comment]
Hi, i view this error:
query_cli.py:116] Failed to login to Hisense server:
Status 404: 'Not Found'
Thanks for your support!

**Comment by deiger** [comment]
OK, turns out that only the region-specific servers work with each app, so oem-eu has to connect to the EU servers.
I've update the script, try now.

**Comment by scaramatto** [comment]
query_cli.py:130] Failed to login to Hisense server:
Status 403: 'Forbidden'

**Comment by scaramatto** [comment]
Problem solved! I have selected the server "oem-eu" instead "mid-eu"!
Thanks!!

**Comment by deiger** [comment]
Excellent!
