### ISSUE TITLE
Comment for properties

### ISSUE THREAD

**Issue by dvdavide** [deiger/AirCon#30]
Courtesy of the hisense-eu app, here are some possible descriptions for the properties that get polled by the script. They are only for the properties that start with "f_e_", as those are the error conditions that the app checks during the diagnostics. It checks for 16 properties, which leaves 4 properties without description. I matched the descriptions to the short name by myself so there might be errors but I think I'm  mostly close.

@deiger Feel free to close this issue after you have seen it as it's not a real issue, thanks again for all of your work.

Property | Comment
--- | ---
f_e_arkgrille | Alarm from cabinet grille protection
f_e_incoiltemp | Indoor coil temperature sensor in fault
f_e_incom | Indoor and outdoor communication in fault
f_e_indisplay | Communication faulty between indoor control panel and display panel
f_e_ineeprom | Error in EEPROM of indoor control panel
f_e_inele | Communication faulty between indoor control panel and indoor power panel
f_e_infanmotor | Indoor fan motor operation abnormal
f_e_inhumidity | Indoor humidity sensor in fault
f_e_inkeys | Communication faulty between indoor control panel and keyboard plate
f_e_inlow | 	
f_e_intemp | Indoor temperature sensor in fault
f_e_invzero | Fault found from indoor voltage crossing zero detection
f_e_outcoiltemp | The temperature sensor in outdoor coil faulty
f_e_outeeprom | Outdoor EEPROM error
f_e_outgastemp | Exhaust temperature sensor faulty
f_e_outmachine2 | 	
f_e_outmachine | 	
f_e_outtemp | Outdoor ambient temperature sensor faulty
f_e_outtemplow | 	
f_e_push | Communication faulty between WiFi control panel and indoor control panel

**Comment by deiger** [comment]
Thanks, adding to the doc.
