### ISSUE TITLE
MQTT values in lowercase, is this expected?

### ISSUE THREAD

**Issue by piejanssens** [deiger/AirCon#35]
Docu in readme shows values in uppercase such as 'ON' or 'COOL'. Via MQTT the message value is 'on' or 'cool'. Is this expected?

<img width="639" alt="Schermafbeelding 2020-08-11 om 19 37 16" src="https://user-images.githubusercontent.com/829098/89929829-16e34c00-dc0a-11ea-9270-668e2be7a043.png">

**Comment by deiger** [comment]
Yes, the values in MQTT are aligned with what HomeAssistant expects, as specified [here](https://www.home-assistant.io/integrations/climate.mqtt/).
