### ISSUE TITLE
README instructions feedback 

### ISSUE THREAD

**Issue by piejanssens** [deiger/AirCon#39]
On my host machine (macOS) the python 3 bin is called `python3` and not `python3.7`.
The current stable version is in fact python 3.8.6. So I'm not sure, but it might be more universal to put instructions in the readme based on `python3` as opposed to `python3.7`.

https://github.com/deiger/AirCon/blame/master/README.md#L46 --> results in error
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/pieter/Projects/AirCon/aircon/__main__.py", line 354, in <module>
    if (len(parsed_args.ip) != len(parsed_args.type) and len(parsed_args.ip) != len(parsed_args.config)):
AttributeError: 'Namespace' object has no attribute 'ip'
```

https://github.com/deiger/AirCon/blame/master/README.md#L59 --> resuts in 'missing argument' 
2 errors:
- Mentioned as parameter device_type instead of type: https://github.com/deiger/AirCon/blame/master/README.md#L66
- Mentiond that 'ac' is the default so one would expect --type to be omittable

https://github.com/deiger/AirCon/blame/master/README.md#L59 --> error after adding `--type ac`
```
raceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/pieter/Projects/AirCon/aircon/__main__.py", line 358, in <module>
    run(parsed_args)
  File "/Users/pieter/Projects/AirCon/aircon/__main__.py", line 296, in run
    device = AcDevice(parsed_args.ip[i], lanip_key, lanip_key_id)
TypeError: __init__() missing 2 required positional arguments: 'lanip_key_id' and 'notifier'
```
Do I have to rename some properties in the config.json from before https://github.com/deiger/AirCon/pull/29?

/cc @karlkar @karolVimn

**Comment by karolVimn** [comment]
You have too remove old version of config.json at all and generate them again by calling discovery.
About other issues I will take a look at them today (hopefully).

**Comment by piejanssens** [comment]
@karolVimn Can you please have a look into the issues?

**Comment by piejanssens** [comment]
Discovery isn't working either. Missing 'retry' lib (in setup.py?)
Needed to run `pip3 install retry` and now I'm having the same error as https://github.com/deiger/AirCon/issues/42

**Comment by piejanssens** [comment]
How can this ever work for you after the last PR?  @deiger @karlkar 
__main__.py:
      `device = AcDevice(parsed_args.ip[i], lanip_key, lanip_key_id)`

These params do not match the constructor's params at all:

aircon.py -- AcDevice:
  `def __init__(self, name: str, ip_address: str, lanip_key: str, lanip_key_id: str,
              notifier: Callable[[None], None]):`

**Comment by wifi75** [comment]
hello, how I can update to last version?

**Comment by deiger** [comment]
Your best option is to just pull the repository from head, run install and regenerate the config using discovery.

**Comment by deiger** [comment]
@piejanssens I've fixed the code at head, it should now be fully functional.

**Comment by piejanssens** [comment]
FYI --type is still mandatory and not mentioned in the README.
