### ISSUE TITLE
Hisense.py line 36

### ISSUE THREAD

**Issue by scaramatto** [deiger/AirCon#4]
Hi, i have successful create 3 Json config file for conditioner.

Example of the file configSalone.json:
{"lanip_key": "sss/xxxxxw==", "lanip_key_id": XXXX, "random_1": "", "time_1": 0, "random_2": "", "time_2": 0}

i try can run the server:
./hisense.py --port 8888 --ip 192.168.0.3 --config configSalone.json --mqtt_host localhost

But when i send command i view this error:

Traceback (most recent call last):
  File "./hisense.py", line 36, in <module>
    from dataclasses_json import dataclass_json
ModuleNotFoundError: No module named 'dataclasses_json'

Any suggestion?

TKS

**Comment by deiger** [comment]
You need to install the additional libraries, as specified in the doc:
```
pip3.7 install dataclasses_json paho-mqtt pycryptodome
```

**Comment by scaramatto** [comment]
Sorry for my continue question, but im not very pratic.
I have successful installated the additionale libraries, but when i send command ./hisense.py --port 8888 --ip 192.168.0.3....

i view this message:

Traceback (most recent call last):
  File "./hisense.py", line 668, in <module>
    logging_handler = logging.handlers.SysLogHandler(address=log_socket)
  File "C:\Program Files\Python37\lib\logging\handlers.py", line 821, in __init__
    self._connect_unixsocket(address)
  File "C:\Program Files\Python37\lib\logging\handlers.py", line 853, in _connect_unixsocket
    self.socket = socket.socket(socket.AF_UNIX, use_socktype)
AttributeError: module 'socket' has no attribute 'AF_UNIX'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\logging\__init__.py", line 2034, in shutdown
    h.close()
  File "C:\Program Files\Python37\lib\logging\handlers.py", line 892, in close
    self.socket.close()
AttributeError: 'SysLogHandler' object has no attribute 'socket'

any ideas? Thanks for cooperation!!!!

**Comment by deiger** [comment]
Ah, didn't test it on Windows...
Try now.

**Comment by scaramatto** [comment]
I'm Sorry for windows system... I've tested but... error:

Traceback (most recent call last):
  File "./hisense.py", line 668, in <module>
    logging_handler = logging.handlers.SysLogHandler(address=log_socket)
  File "C:\Program Files\Python37\lib\logging\handlers.py", line 821, in __init__
    self._connect_unixsocket(address)
  File "C:\Program Files\Python37\lib\logging\handlers.py", line 853, in _connect_unixsocket
    self.socket = socket.socket(socket.AF_UNIX, use_socktype)
AttributeError: module 'socket' has no attribute 'AF_UNIX'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\logging\__init__.py", line 2034, in shutdown
    h.close()
  File "C:\Program Files\Python37\lib\logging\handlers.py", line 892, in close
    self.socket.close()
AttributeError: 'SysLogHandler' object has no attribute 'socket'

Tks

**Comment by deiger** [comment]
Did you download the script again? I've updated it with a fix for the logging handler for Windows.

**Comment by scaramatto** [comment]
Ok, Sorry... but:

Traceback (most recent call last):
  File "./hisense.py", line 689, in <module>
    _mqtt_topics['pub'] = os.path.join(_parsed_args.mqtt_topic, 'status')
NameError: name 'os' is not defined

**Comment by deiger** [comment]
Oops, sorry, added the missing import.

**Comment by scaramatto** [comment]
WORKING!!

192.168.0.20 - - [15/Oct/2019 14:50:04] "POST /local_lan/property/datapoint.json?cmd_id=43&status=200 HTTP/1.1" 200 -
192.168.0.20 - - [15/Oct/2019 14:50:04] "GET /local_lan/commands.json HTTP/1.1" 200 -
192.168.0.20 - - [15/Oct/2019 14:51:45] "GET /local_lan/commands.json HTTP/1.1" 200 -
192.168.0.20 - - [15/Oct/2019 14:53:25] "GET /local_lan/commands.json HTTP/1.1" 200 -

Now i'm trying to look for it in Home Assistant MQTT-Mosquitto broker but only view the login :\

**Comment by scaramatto** [comment]
Hi, i have inserted the link: http: // localhost: 8888 / hisense / command? property = t_power & value = ON... and command work! I have a question, how i can send command for a specific conditoner? Because i have 3 conditoners... Thks

**Comment by deiger** [comment]
You should start 3 services, each on a separate port, MQTT paths and AC config.
Since Python isn't good at multithreading, the best option would be multi-process anyway, and this way each AC service is isolated from the others.
