### ISSUE TITLE
Home assistant, I have implemented the config yaml that you gave but...

### ISSUE THREAD

**Issue by refaelsommer** [deiger/AirCon#41]
Hello,

I have 6 Aircons working with the app טורנדו (tornado-us) and I want to make them work on home assistant, but I don't have all the info to do that,
where do I give the mac or IP?
what do I need to install and how?

Can you please help me understand?

Thanks! 👍 
Refael.S

**Comment by deiger** [comment]
Hi,

I've just implemented MQTT Discovery for HomeAssistant, so if you install the updated version, it will auto populate HomeAssistant.
You do need to run discovery and create configs for all the ACs, but once the setup of the server is done, HA will be fully aware of them.

Dror

**Comment by refaelsommer** [comment]
Thanks, I
Managed to make it work.
Installed MQTT gave it a port and it automatically showed me all 6 Aircons
Then installed hisense in supervisor and now it all works.
