### ISSUE TITLE
AttributeError using discovery, 'Namespace' object has no attribute 'ip'

### ISSUE THREAD

**Issue by Corne008** [deiger/AirCon#42]
Hi,
Very excited to see this solution. Unfortunately the discovery command returns an error.

python3.7 -m aircon discovery fglair-eu me@email.com mypwd

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/aircon-0.0.1-py3.7.egg/aircon/__main__.py", line 354, in <module>
AttributeError: 'Namespace' object has no attribute 'ip'

Hope you can help me out here.

**Comment by piejanssens** [comment]
I commented out L354 + L355 in aircon/__main__.py as woraround.

**Comment by Corne008** [comment]
Thanks, this helped, I have the information on screen. 
==============
Device AC000W00xxxxxxxxx has:
IP address: 192.168.2.xxx
lanip_key: HMcHqxxxxxNcL5/Vniv3xxxx4A==
lanip_key_id: abcd
===============
Since no config.json was created I did that myself with these lines. I don't know if that is correct.

Second question, where can I find the portnumber to use with the --port parameter?

Thanks in advance.

**Comment by deiger** [comment]
Fixed the code.
The port is for the web server, not really relevant if you use HA (so just set it to something random above 10000).
