### ISSUE TITLE
I CANT

### ISSUE THREAD

**Issue by zeroincondotta** [deiger/AirCon#44]
non riesco ad integrare proprio i condizionatori, sto provando in vari modi ad eseguire i comandi ma sembra proprio che non vadano o sono io che non li so eseguire. ma tale guida va bene per l'istallazione hassio? io ho home assistant , non il core. e provo ad eseguire i comandi con terminale , ho anche provato a creare io i file ma non mi esce nulla.

**Comment by deiger** [comment]
Hi, please try again now. The code was broken, but is now fixed.
You should be able to run the installation (after a git clone), set up the server, and the ACs will appear in Home Assistant.

**Comment by zeroincondotta** [comment]
Posso usare tale guida lanciando questi comandi da terminale di home assistant?

**Comment by deiger** [comment]
No, I'm afraid you need to ssh the system itself. It cannot run in HA's internal terminal, as it is restricted to the docker.

**Comment by zeroincondotta** [comment]
se seguo tale guida , istallando python su windows e lavoro dal terminale win poi le entità le trovo su HA ???

**Comment by deiger** [comment]
Yes. Though are you running HA on Windows? Raspberry Pi is a far better fit for HA (and for this server), if only for the electricity charges it will allow you to avoid.

**Comment by zeroincondotta** [comment]
no, HA lo ho su rasp, ma come hai detto tu , sul terminale interno non vanno i comandi.
devo avviare una connessione ssh tramite qualche software

**Comment by deiger** [comment]
Then just use an ssh software (like PuTTY) to connect the the hosting platform on the Raspberry Pi, and you can install everything.

**Comment by zeroincondotta** [comment]
è vergognoso dirlo, ma non c'è modo di collegarsi con putty, è un mese che provo, eppure ho istallato in modo corretto l'addon e il terminale su _Ha funziona, ma tramite putty non si collega

**Comment by zeroincondotta** [comment]
ho provato a lanciare i comandi da terminale interno
 git clone https://github.com/deiger/AirCon
 cd AirCon
 python3.8 setup.py install
mi ha creato la cartella Aircon dentro la cartella custom component e ho 4 file 
config.json
hisense.py
query_cli.py
setup.py

è meglio proseguire quando sono in LAN ???

**Comment by giustanca** [comment]
ciao zeroincondotta... io come te sto andando a tentativi....con "python3.7 setup.py..." non va. Allora ho provato con il python3.8 ed è partito...ma alla fine mi risultano degli errori e non trovo la cartella Aircon da nessun parte. A te risultano errori dopo il comando di setup?

**Comment by zeroincondotta** [comment]
![confi3page](https://user-images.githubusercontent.com/74971714/103305534-acda1080-4a0b-11eb-8749-44b92fb97b43.PNG)
![confi2page](https://user-images.githubusercontent.com/74971714/103305540-ae0b3d80-4a0b-11eb-951e-fc8c31692f95.PNG)
![confi1page](https://user-images.githubusercontent.com/74971714/103305543-aea3d400-4a0b-11eb-8c46-eb108e227f0d.PNG)

**Comment by zeroincondotta** [comment]
> ciao zeroincondotta... io come te sto andando a tentativi....con "python3.7 setup.py..." non va. Allora ho provato con il python3.8 ed è partito...ma alla fine mi risultano degli errori e non trovo la cartella Aircon da nessun parte. A te risultano errori dopo il comando di setup?

a me la cartella aircon l'ha creata dentro la cartella custom component

**Comment by zeroincondotta** [comment]
se lancio il comando discovery 
python3.8 -m aircon discovery hisense-eu foo@example.com my_pass 
parte ma non restituisce nulla
forse pero va fatta sotto lan
