### ISSUE TITLE
missing 2 arguments?

### ISSUE THREAD

**Issue by dovrose** [deiger/AirCon#45]
Hi,

Just tried to run the server, and had some problem with the function, the discovery run without any issue.

What is missing?

device = AcDevice(parsed_args.ip[i], lanip_key, lanip_key_id)
TypeError: __init__() missing 2 required positional arguments: 'lanip_key_id' and 'notifier'

I run the server as following:
 sudo python3 -m aircon run --port 8888 --ip xxx.xxx.xxx.xxx --config config_livingroom.json --type ac --mqtt_host yyy.yyy.yyy.yyy --mqtt_port 1883 --mqtt_user user:password

Thank you 
Dov

**Comment by deiger** [comment]
Hi Dov,

The code was broken by a pull request I got. It's fixed now, with the added benefit of MQTT Discovery.

Dror

**Comment by dovrose** [comment]
Thank you !!!
it's working now.

BTW, it's working with AEH-W4F1 with Tornado AC.
Also, I have my server working on ubuntu (undrer proxmox), I notesed, it needed to restart evey few hours, so I added crontab job to handel it.
and again, Thank you.
![image](https://user-images.githubusercontent.com/4309253/103629092-8e62a080-4f48-11eb-8255-1dc4f754ba19.png)

Dov

**Comment by deiger** [comment]
Excellent. I hope the recent changes stabilized it.
