### ISSUE TITLE
Error occurred. during discovery process

### ISSUE THREAD

**Issue by gcampagnoli** [deiger/AirCon#46]
Hi, thanks for the update, but now during discovery process, find my devices, but failed with a generic error,

Error occurred.

`--- build/lib/aircon/__main__.py        2020-12-27 19:34:44.000000000 +0100
+++ aircon/__main__.py  2020-12-27 19:38:30.989961055 +0100
@@ -243,7 +243,8 @@
                                             parsed_args.passwd, parsed_args.prefix,
                                             parsed_args.device,
                                             parsed_args.properties)
-    except:
+    except Exception as ex:
+      print(ex)
       print('Error occurred.')
       sys.exit(1)
`

Is missing async in perform_discovery in discovery.py

--- build/lib/aircon/discovery.py       2020-12-27 19:34:44.000000000 +0100
+++ aircon/discovery.py 2020-12-27 19:40:12.689961016 +0100
@@ -104,7 +104,7 @@
     pass  # Not gzipped.
   return json.loads(resp_data)

-def perform_discovery(app: str, user: str, passwd: str,
+async def perform_discovery(app: str, user: str, passwd: str,
                      prefix: str, device_filter: str,
                      properties_filter: bool) -> dict:
   if app in SECRET_ID_MAP:

**Comment by deiger** [comment]
Thanks for the issue, this should now be fixed.

**Comment by SvenStorck** [comment]
I can confirm that it works now without the generic error and creates a config file!

ty
