### ISSUE TITLE
Simplify run command

### ISSUE THREAD

**Issue by piejanssens** [deiger/AirCon#48]
`--ip`is the same IP as defined in the config, so it could be read from the config and left out from the params
`--type` could be defaulted to `ac` as intended and described in the README

**Comment by deiger** [comment]
`--type` indeed used to be defaulted to `ac`, however as part of the support for multiple ACs, all relevant flags became required, so each is attributed to the right AC. I'll change the README accordingly.
`--ip` may indeed be read from the config.
