### ISSUE TITLE
New MQTT topic sub path

### ISSUE THREAD

**Issue by piejanssens** [deiger/AirCon#49]
I'm seeing all topics being published under `hisense_ac/ca2c4f5f18c3`
Where is this `ca2c4f5f18c3` coming from? Is it a bug or intentional? How is this ID determined? Is it a stable ID?

<img width="1025" alt="Schermafbeelding 2020-12-29 om 12 10 04" src="https://user-images.githubusercontent.com/829098/103279906-4afbb580-49cf-11eb-8258-81dae0b635d8.png">

**Comment by deiger** [comment]
This is the AC's MAC address. It is a stable ID that is guaranteed to be unique, and won't be affected by user changes (like a rename of the device). Zigbee2mqtt is using the same trick for their broadcast.
