### ISSUE TITLE
FGL Air issue

### ISSUE THREAD

**Issue by Corne008** [deiger/AirCon#53]
Hi, I have about the same issue as in https://github.com/deiger/AirCon/issues/16#issuecomment-753368676_ .... but fgl_b doesn't resolve my problem ;-)
Our Fijutsi UTY-TFSXW1 WiFi module returns 

HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Content-Length: 205
Date: Fri, 01 Jan 2021 18:45:42 GMT
Server: Python/3.7 aiohttp/3.6.2

{"devices": [{"ip": "192.168.2.107", "props": {"operation_mode": "OFF", "fan_speed": "AUTO", "adjust_temperature": 210, "af_vertical_move_step1": 3, "af_horizontal_move_step1": 3, "economy_mode": "OFF"}}]}

with the command: curl -ik 'http://192.168.2.252:10000/hisense/status'

with the 
curl -ik 'http://192.168.2.252:10000/hisense/command?property=operation_mode&value=ON'
the output is 'Bad Request'.
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Content-Length: 16
Date: Fri, 01 Jan 2021 18:45:53 GMT
Server: Python/3.7 aiohttp/3.6.2

Using the remote control to turn the AC on the MQTT message is "hisense_ac/a0cc2bf0xxxxx/operation_mode/status auto"

Any idea if it is possible to control the AC using curl or mosquitto_pub?

Thanx...

_Originally posted by @Corne008 in https://github.com/deiger/AirCon/issues/16#issuecomment-753368676_

**Comment by deiger** [comment]
It is possible, through both MQTT and curl. In curl you need to pass the property name as specified [here](https://github.com/deiger/AirCon#available-properties). The MQTT setup is according to HomeAssistant's spec, detailed [here](https://www.home-assistant.io/integrations/climate.mqtt/).

**Comment by Corne008** [comment]
Hi deiger, 
First of all, thanks for your reply.
But unfortunatily I keep getting the Bad request using curl (in both cases of --type fgl and fgl_b)
curl -ik 'http://192.168.2.252:10000/hisense/command?property=operation_mode&value=ON'

**HTTP/1.1 400 Bad Request**
Content-Type: text/plain; charset=utf-8
Content-Length: 16
Date: Fri, 01 Jan 2021 18:45:53 GMT
Server: Python/3.7 aiohttp/3.6.2

3 questions for now:
- Regarding the UTY-TFSXW1 WiFi module should I use --type fgl or fgl_b
- did you notice the extra levels in the curl status output? {**"devices": [{"ip": "192.168.2.107", "props":** {"operation_mode": "OFF", "fan_speed": "AUTO", "adjust_temperature": 210, "af_vertical_move_step1": 3, "af_horizontal_move_step1": 3, "economy_mode": "OFF"}}]}
-  and why do I get the Bad Request error?

I'm not familiar wih Home Assistent, I want to integrate your solution in Domoticz.

Thanks in advance.

**Comment by deiger** [comment]
Regarding UTY-TFSXW1, I'm not sure, looking into the FGLair app, there should be an underlying OEM model. Could you please detail what appears in the config file generated in discovery?
The added level was added in a recent PR, it's part of the support for multiple A/Cs.
I'm not sure about the Bad request, can you look into the logs if there is something relevant?
What is the protocol for Domoticz, does it support MQTT?

**Comment by deiger** [comment]
In the recent version you should no longer need to choose between fgl and fgl_b, it's deriving that from the OEM model.

**Comment by Corne008** [comment]
**Configfile:**
{"name": "AC000W999995716", "app": "fglair-eu", "model": "AP-WD1E", "sw_version": "bc 2.6.17-fgl2 06/29/20 09:03:57 ID jre/mfg/2dfbf5d", "dsn": "AC000W999995716", "mac_address": "a0cc2bfff999", "ip_address": "192.168.2.107", "lanip_key": "HMcHq7K8faMNcL5/Vniv3Afj3t666666", "lanip_key_id": 1199}

For your information, we have 3 units.. I'm trying with only one for now ;-)

**syslog entry:**
Jan 13 19:39:49 raspberrypi E0113 19:39:49.161  web_protocol.py:355] Error handling request#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.7/dist-packages/aiohttp-3.6.2-py3.7.egg/aiohttp/web_protocol.py", line 418, in start#012    resp = await task#012  File "/usr/local/lib/python3.7/dist-packages/aiohttp-3.6.2-py3.7.egg/aiohttp/web_app.py", line 458, in _handle#012    resp = await handler(request)#012  File "/home/pi/AirCon/aircon/query_handlers.py", line 72, in property_update_handler#012    update = self._decrypt_and_validate(device, data)#012  File "/home/pi/AirCon/aircon/query_handlers.py", line 133, in _decrypt_and_validate#012    return json.loads(text.decode('utf-8'))#012  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads#012    return _default_decoder.decode(s)#012  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode#012    obj, end = self.raw_decode(s, idx=_w(s, 0).end())#012  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode#012    obj, end = self.scan_once(s, idx)#012json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 22 (char 21)

Domoticz is able to support MQTT. That is how I want to do the implementation in Domoticz.

**Comment by stefaanbolle** [comment]
Try with the latest git pull. FGLair-EU is working now

**Comment by deiger** [comment]
I've changed the code to log the json that did not parse, in case it happens again.

**Comment by Corne008** [comment]
Hi Deiger, that did it. I can send the curl commands and I also see the mqtt messages passing..
Thanks for your work!
