### ISSUE TITLE
Temperature units in MQTT auto-discover

### ISSUE THREAD

**Issue by dvdavide** [deiger/AirCon#54]
My unit with the AEH-W4B1 works as expected, the units with the W4E1 display negative values for set temperature and ambient temperature.
I think there might be a unit conversion missing somewhere, or actually one too many, since the entity comes out fine if I reuse the manual configuration I used to have, which has no unit conversion for the W4E1 units.

Other than that, from what I could test everything is working much better than before, thanks again for the great job.

**Comment by deiger** [comment]
Thanks for the input!
I guess the issue is that the W4E1 units are internally based in Celsius, while the W4B1 are in Fahrenheit.
Which app are you using for each?

**Comment by dvdavide** [comment]
oem-eu for the W4B1, hisense-eu for the W4E1.
And yes, I'd like to have the temperature displayed in Celsius :)

**Comment by deiger** [comment]
Everyone in the "normal world does" - it's just that the API works mostly in Fahrenheit (because if you want to support both, you'd better go for the higher precision one).
I've changed the code to add a temp_type to the config on discovery. Please try it out.
