### ISSUE TITLE
Help to integrate into Openhab3 MQTT

### ISSUE THREAD

**Issue by stefaanbolle** [deiger/AirCon#58]
Who can assist in how to integrate Aircon in Openhab MQTT?
I have define a generic MQTT thing for my FGLAir airco and I receive all changes in /status topics as attached.

However by no means I can give commands to the unit via these mqtt /command topics.

![Screenshot 2021-01-07 at 15 38 54](https://user-images.githubusercontent.com/6658848/103905236-a7ad4d80-50fe-11eb-86bc-c4c2058cad8c.jpg)

**Comment by deiger** [comment]
That's what homeassistant/climate/a0c9a00de828/hvac/config is there for. Both status and command topics are listed there.
I'm not aware of a dedicated support for MQTT auto-discoveryin openHAB, however there is a [HomeAssistant MQTT Components Binding](https://www.openhab.org/addons/bindings/mqtt.homeassistant/) extension, that should do the trick here.

**Comment by stefaanbolle** [comment]
I will try that.
When I do curl -ik 'http://localhost:8888/hisense/status'                                                                          7 master?
```
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Content-Length: 261
Date: Fri, 08 Jan 2021 06:43:22 GMT
Server: Python/3.7 aiohttp/3.6.2

{"devices": [{"ip": "192.168.1.38", "props": {"operation_mode": "HEAT", "fan_speed": "AUTO", "adjust_temperature": 220, "af_vertical_direction": 4, "af_vertical_swing": "OFF", "af_horizontal_direction": 0, "af_horizontal_swing": "OFF", "economy_mode": "OFF"}}]}%
```

I get correct output, however curl -ik 'http://localhost:8888/hisense/command?property=t_work_mode&value=HEAT'
gives
```
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Content-Length: 16
Date: Fri, 08 Jan 2021 06:45:07 GMT
Server: Python/3.7 aiohttp/3.6.2

400: Bad Request%
```
Maybe commands are not being accepted (FGLAir with W1D devices)

**Comment by deiger** [comment]
What appears in the syslog when you get the 400 error?
It should have more info.

**Comment by stefaanbolle** [comment]
Actually nothing :-(

**Comment by deiger** [comment]
OK, I've pushed an update that should bring the log data to you in the 400 response.
Try pulling and run again.

**Comment by stefaanbolle** [comment]
curl -ik 'http://localhost:8888/hisense/command?property=t_work_mode&value=HEAT'                                           master?
```
HTTP/1.1 400 Device "None" not found.
Content-Type: text/plain; charset=utf-8
Content-Length: 29
Date: Fri, 08 Jan 2021 10:07:37 GMT
Server: Python/3.7 aiohttp/3.6.2

400: Device "None" not found.%
```

**Comment by stefaanbolle** [comment]
curl -ik 'http://localhost:8888/hisense/status'
```
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Content-Length: 261
Date: Fri, 08 Jan 2021 10:08:44 GMT
Server: Python/3.7 aiohttp/3.6.2

{"devices": [{"ip": "192.168.1.38", "props": {"operation_mode": "HEAT", "fan_speed": "AUTO", "adjust_temperature": 220, "af_vertical_direction": 4, "af_vertical_swing": "OFF", "af_horizontal_direction": 0, "af_horizontal_swing": "OFF", "economy_mode": "OFF"}}]}%
```

**Comment by deiger** [comment]
Hmm.. Please try:
```
curl -ik 'http://localhost:8888/hisense/command?device_ip=192.168.1.38&property=t_work_mode&value=HEAT'
```
I think this was broken in the last pull request.

**Comment by stefaanbolle** [comment]
curl -ik 'http://localhost:8888/hisense/command?device_ip=192.168.1.38&property=t_work_mode&value=HEAT' 
```
HTTP/1.1 500 Internal Server Error
Content-Type: text/plain; charset=utf-8
Content-Length: 55
Date: Fri, 08 Jan 2021 14:36:27 GMT
Server: Python/3.7 aiohttp/3.6.2
Connection: close

500 Internal Server Error

Server got itself in trouble%
```

**Comment by stefaanbolle** [comment]
Any clue on how I could resolve below error?
```
500 Internal Server Error
Server got itself in trouble%
```

**Comment by deiger** [comment]
I've removed the need for device_ip when there is a single A/C. Try updating?

**Comment by stefaanbolle** [comment]
I did a git pull and restarted the airco service.
curl -ik 'http://localhost:8889/hisense/status'  
gives
```
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Content-Length: 260
Date: Tue, 12 Jan 2021 19:55:22 GMT
Server: Python/3.7 aiohttp/3.6.2

{"devices": [{"ip": "192.168.1.35", "props": {"operation_mode": "AUTO", "fan_speed": "AUTO", "adjust_temperature": 25, "af_vertical_direction": 3, "af_vertical_swing": "OFF", "af_horizontal_direction": 3, "af_horizontal_swing": "OFF", "economy_mode": "OFF"}}]}%
```
curl -ik 'http://localhost:8889/hisense/command?property=operation_mode&value=HEAT'
gives 
```
HTTP/1.1 500 Internal Server Error
Content-Type: text/plain; charset=utf-8
Content-Length: 55
Date: Tue, 12 Jan 2021 19:56:09 GMT
Server: Python/3.7 aiohttp/3.6.2
Connection: close

500 Internal Server Error

```

**Comment by stefaanbolle** [comment]
I also tried to write  the service to include all aircos in 1 line. So IP must be included in that case I assume?
curl -ik 'http://localhost:8889/hisense/command?device_ip=192.168.1.38&property=t_work_mode&value=HEAT'
gives
```

HTTP/1.1 500 Internal Server Error
Content-Type: text/plain; charset=utf-8
Content-Length: 55
Date: Fri, 08 Jan 2021 14:36:27 GMT
Server: Python/3.7 aiohttp/3.6.2
Connection: close

500 Internal Server Error

Server got itself in trouble%

```

**Comment by stefaanbolle** [comment]
After git pull to 0.3.5 by git pull and rerunning install.
Discovery runs fine again, thanks!

The command to control the unit still gives the same error.
I now use one hisense.service to control 4 units with 1 http port (8889) in stead of 4 different servers for each unit one.

sudo curl -ik 'http://localhost:8889/hisense/command?device_ip=192.168.1.38&property=t_work_mode&value=HEAT'
```
HTTP/1.1 500 Internal Server Error
Content-Type: text/plain; charset=utf-8
Content-Length: 55
Date: Wed, 13 Jan 2021 14:13:32 GMT
Server: Python/3.7 aiohttp/3.6.2
Connection: close

500 Internal Server Error

Server got itself in trouble%

```

**Comment by stefaanbolle** [comment]
curl -ik 'http://localhost:8889/hisense/command?device_ip=192.168.1.38&property=t_work_mode&value=HEAT'
Regarding fglair:
- Is t_work_mode the correct command or is operation_mode needed?
- Do I select which device to control via parameter device_id or do I have to use the device name (AC000W002881411) and if so, how do I pass this parameter?

**Comment by deiger** [comment]
Yes, `operation_mode` is the right command for FGLair.
In `curl` device IP should be your way to choose the relevant device. It would probably be cleaner to use the MAC address, as done in MQTT.

**Comment by stefaanbolle** [comment]
> Yes, `operation_mode` is the right command for FGLair.
> In `curl` device IP should be your way to choose the relevant device. It would probably be cleaner to use the MAC address, as done in MQTT.

Could you give the exact curl command to turn on a W1DE FGLAIR unit with ip 192.168.1.38 and mac AA:BB:CC:DD:EE:FF listening on port 8889 (which is used by 4 equal units)?

**Comment by stefaanbolle** [comment]
It is working now since the latest patch. Thanks!!
