### ISSUE TITLE
Service not  working

### ISSUE THREAD

**Issue by wifi75** [deiger/AirCon#59]
Hello @deiger , on my Ubuntu server machine I have two AC on my hisense.service file it is correct line below:

**python3.7 -m aircon run -p 8887 --type ac --config config_stanzetta.json --type ac --config config_studio.json --mqtt_host 192.168.1.52 --mqtt_user mqtt_user:mypassword**

maybe something is missing?

after start service there is this error:
![image](https://user-images.githubusercontent.com/31816231/104004338-eb0dc780-51a3-11eb-9a8b-ea7f2dedfabf.png)

thi is my code n ubuntu machine:

```
[Unit]
Description=Script clima Hisense 
After=docker.service

[Service]
ExecStart=/usr/bin/python3.7 -m aircon run --port 8887 --type ac --config config_stanzetta.json --type ac --config config_studio.json --mqtt_host 192.168.1.52 --mqtt_user mqtt_user:mypassword
WorkingDirectory=/usr/lib/hisense
StandardOutput=inherit
StandardError=inherit
Restart=always

[Install]
WantedBy=multi-user.target


ps.

manually with this code work and no problem, why?

python3.7 -m aircon run --port 8887 --config config_studio.json --type ac --type ac --config config_stanzetta.json --mqtt_host 192.168.1.52 --mqtt_user mqtt_user:mypassword
```

**Comment by deiger** [comment]
Are you seeing anything in the logs?
If you use journald (by running `sudo apt install python3-systemd`), the log will be available in a cleaner form in `journalctl`.

**Comment by wifi75** [comment]
@deiger 

below log :

```
Jan  8 14:04:38 ubuntu-server systemd[1]: hisense.service: Service hold-off time over, scheduling restart.
Jan  8 14:04:38 ubuntu-server systemd[1]: hisense.service: Scheduled restart job, restart counter is at 1.
Jan  8 14:04:38 ubuntu-server systemd[1]: Stopped Script clima Hisense.
Jan  8 14:04:38 ubuntu-server systemd[1]: Started Script clima Hisense.
Jan  8 14:04:39 ubuntu-server python3.7[1096]: Traceback (most recent call last):
Jan  8 14:04:39 ubuntu-server python3.7[1096]:   File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
Jan  8 14:04:39 ubuntu-server python3.7[1096]:     "__main__", mod_spec)
Jan  8 14:04:39 ubuntu-server python3.7[1096]:   File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
Jan  8 14:04:39 ubuntu-server python3.7[1096]:     exec(code, run_globals)
Jan  8 14:04:39 ubuntu-server python3.7[1096]:   File "/usr/local/lib/python3.7/dist-packages/aircon-0.0.1-py3.7.egg/aircon/__main__.py", line 289, in <module>
Jan  8 14:04:39 ubuntu-server python3.7[1096]:   File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
Jan  8 14:04:39 ubuntu-server python3.7[1096]:     return loop.run_until_complete(main)
Jan  8 14:04:39 ubuntu-server python3.7[1096]:   File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
Jan  8 14:04:39 ubuntu-server python3.7[1096]:     return future.result()
Jan  8 14:04:39 ubuntu-server python3.7[1096]:   File "/usr/local/lib/python3.7/dist-packages/aircon-0.0.1-py3.7.egg/aircon/__main__.py", line 170, in run
Jan  8 14:04:39 ubuntu-server python3.7[1096]:   File "/usr/local/lib/python3.7/dist-packages/aircon-0.0.1-py3.7.egg/aircon/aircon.py", line 195, in __init__
Jan  8 14:04:39 ubuntu-server python3.7[1096]:   File "/usr/local/lib/python3.7/dist-packages/aircon-0.0.1-py3.7.egg/aircon/aircon.py", line 25, in __init__
Jan  8 14:04:39 ubuntu-server python3.7[1096]: KeyError: 'app'
Jan  8 14:04:39 ubuntu-server cloud-init[1094]: Cloud-init v. 20.4-0ubuntu1~18.04.1 running 'modules:config' at Fri, 08 Jan 2021 13:04:39 +0000. Up 12.33 seconds.
Jan  8 14:04:39 ubuntu-server systemd[1]: hisense.service: Main process exited, code=exited, status=1/FAILURE
Jan  8 14:04:39 ubuntu-server systemd[1]: hisense.service: Failed with result 'exit-code'.
Jan  8 14:04:39 ubuntu-server systemd[1]: Started Apply the settings specified in cloud-config.
Jan  8 14:04:39 ubuntu-server systemd[1]: Starting Execute cloud user/final scripts...
Jan  8 14:04:39 ubuntu-server systemd[1]: hisense.service: Service hold-off time over, scheduling restart.
Jan  8 14:04:39 ubuntu-server systemd[1]: hisense.service: Scheduled restart job, restart counter is at 2.
Jan  8 14:04:39 ubuntu-server systemd[1]: Stopped Script clima Hisense.
Jan  8 14:04:39 ubuntu-server systemd[1]: Started Script clima Hisense.
Jan  8 14:04:40 ubuntu-server systemd[1]: hassio-supervisor.service: Service hold-off time over, scheduling restart.
Jan  8 14:04:40 ubuntu-server systemd[1]: hassio-supervisor.service: Failed to schedule restart job: Unit docker.service is masked.
Jan  8 14:04:40 ubuntu-server systemd[1]: hassio-supervisor.service: Failed with result 'exit-code'.
Jan  8 14:04:40 ubuntu-server python3.7[1171]: Traceback (most recent call last):
Jan  8 14:04:40 ubuntu-server python3.7[1171]:   File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
Jan  8 14:04:40 ubuntu-server python3.7[1171]:     "__main__", mod_spec)
Jan  8 14:04:40 ubuntu-server python3.7[1171]:   File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
Jan  8 14:04:40 ubuntu-server python3.7[1171]:     exec(code, run_globals)
Jan  8 14:04:40 ubuntu-server python3.7[1171]:   File "/usr/local/lib/python3.7/dist-packages/aircon-0.0.1-py3.7.egg/aircon/__main__.py", line 289, in <module>
Jan  8 14:04:40 ubuntu-server python3.7[1171]:   File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
Jan  8 14:04:40 ubuntu-server python3.7[1171]:     return loop.run_until_complete(main)
Jan  8 14:04:40 ubuntu-server python3.7[1171]:   File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
Jan  8 14:04:40 ubuntu-server python3.7[1171]:     return future.result()
Jan  8 14:04:40 ubuntu-server python3.7[1171]:   File "/usr/local/lib/python3.7/dist-packages/aircon-0.0.1-py3.7.egg/aircon/__main__.py", line 170, in run
Jan  8 14:04:40 ubuntu-server python3.7[1171]:   File "/usr/local/lib/python3.7/dist-packages/aircon-0.0.1-py3.7.egg/aircon/aircon.py", line 195, in __init__
Jan  8 14:04:40 ubuntu-server python3.7[1171]:   File "/usr/local/lib/python3.7/dist-packages/aircon-0.0.1-py3.7.egg/aircon/aircon.py", line 25, in __init__
Jan  8 14:04:40 ubuntu-server python3.7[1171]: KeyError: 'app'
Jan  8 14:04:40 ubuntu-server cloud-init[1160]: Cloud-init v. 20.4-0ubuntu1~18.04.1 running 'modules:final' at Fri, 08 Jan 2021 13:04:40 +0000. Up 13.49 seconds.
Jan  8 14:04:40 ubuntu-server cloud-init[1160]: Cloud-init v. 20.4-0ubuntu1~18.04.1 finished at Fri, 08 Jan 2021 13:04:40 +0000. Datasource DataSourceNoCloud [seed=/var/lib/cloud/seed/nocloud-net][dsmode=net].  Up 13.71 seconds
Jan  8 14:04:40 ubuntu-server systemd[1]: hisense.service: Main process exited, code=exited, status=1/FAILURE
Jan  8 14:04:40 ubuntu-server systemd[1]: hisense.service: Failed with result 'exit-code'.
Jan  8 14:04:40 ubuntu-server systemd[1]: Started Execute cloud user/final scripts.
Jan  8 14:04:40 ubuntu-server systemd[1]: Reached target Cloud-init target.
Jan  8 14:04:40 ubuntu-server systemd[1]: Startup finished in 2.652s (kernel) + 11.167s (userspace) = 13.820s.
Jan  8 14:04:41 ubuntu-server systemd[1]: hisense.service: Service hold-off time over, scheduling restart.
Jan  8 14:04:41 ubuntu-server systemd[1]: hisense.service: Scheduled restart job, restart counter is at 3.
Jan  8 14:04:41 ubuntu-server systemd[1]: Stopped Script clima Hisense.
Jan  8 14:04:41 ubuntu-server systemd[1]: Started Script clima Hisense.
Jan  8 14:04:41 ubuntu-server python3.7[1258]: Traceback (most recent call last):
Jan  8 14:04:41 ubuntu-server python3.7[1258]:   File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
Jan  8 14:04:41 ubuntu-server python3.7[1258]:     "__main__", mod_spec)
Jan  8 14:04:41 ubuntu-server python3.7[1258]:   File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
Jan  8 14:04:41 ubuntu-server python3.7[1258]:     exec(code, run_globals)
Jan  8 14:04:41 ubuntu-server python3.7[1258]:   File "/usr/local/lib/python3.7/dist-packages/aircon-0.0.1-py3.7.egg/aircon/__main__.py", line 289, in <module>
Jan  8 14:04:41 ubuntu-server python3.7[1258]:   File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
Jan  8 14:04:41 ubuntu-server python3.7[1258]:     return loop.run_until_complete(main)
Jan  8 14:04:41 ubuntu-server python3.7[1258]:   File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
Jan  8 14:04:41 ubuntu-server python3.7[1258]:     return future.result()
Jan  8 14:04:41 ubuntu-server python3.7[1258]:   File "/usr/local/lib/python3.7/dist-packages/aircon-0.0.1-py3.7.egg/aircon/__main__.py", line 170, in run
Jan  8 14:04:41 ubuntu-server python3.7[1258]:   File "/usr/local/lib/python3.7/dist-packages/aircon-0.0.1-py3.7.egg/aircon/aircon.py", line 195, in __init__
Jan  8 14:04:41 ubuntu-server python3.7[1258]:   File "/usr/local/lib/python3.7/dist-packages/aircon-0.0.1-py3.7.egg/aircon/aircon.py", line 25, in __init__
```

**Comment by deiger** [comment]
`KeyError: 'app'`?? Apparently it could not find the app in the config dictionary. Is it there?

**Comment by wifi75** [comment]
can you explain what I have to do?

**Comment by deiger** [comment]
Print your config files. Are you seeing the app key in them?

**Comment by wifi75** [comment]
@deiger 
I have two config, for two ac:

`{"name": "Stanzetta", "app": "hisense-eu", "model": "Smart-1-110-eu", "sw_version": "ADA 1.4.3-beta ameba 2018-03-28 19:20:06 8f40fe89d", "dsn": "AC000W006587674", "temp_type": "C", "mac_address": "ca2c4f5ee378", "ip_address": "192.168.1.19", "lanip_key": "4aerVa0KzRcczxUkXJB/E61r1oDT1g==", "lanip_key_id": 54903}`

`{"name": "Studio", "app": "hisense-eu", "model": "Smart-1-110-eu", "sw_version": "ADA 1.4.3-beta ameba 2018-03-28 19:20:06 8f40fe89d", "dsn": "AC000W006586835", "temp_type": "C", "mac_address": "ca2c4f5ee031", "ip_address": "192.168.1.18", "lanip_key": "dtD4Qv4C5hrM76WOzojjpeLGz3wFyQ==", "lanip_key_id": 58205}`

**Comment by wifi75** [comment]
Solved!!!!! I copy again file config to /usr/lib/hisense/ folderand nowit is ok!

**Comment by deiger** [comment]
Cool, that was my guess, that these were different files.

**Comment by wifi75** [comment]
Only one think, how i can set two different topic on hisense.service file ?

**Comment by deiger** [comment]
You only define the prefix. The actual topics include the MAC address for each AC. You will see everything correctly in HA due to MQTT Discovery.
Yes, this is normal, I'll remove these error logs.

**Comment by dovrose** [comment]
Hi,

I have similer/difrent problem:
after starting the service, it's working. and after few 2 min, i have this error:
`Jan 09 17:30:03 AvirconV2 python3[2287]: E0109 17:30:03.502  web_protocol.py:355] Error handling request
                                         Traceback (most recent call last):
                                           File "/usr/local/lib/python3.8/dist-packages/aiohttp-3.6.2-py3.8.egg/aiohttp/web_protocol.py", line 418, in start
                                             resp = await task
                                           File "/usr/local/lib/python3.8/dist-packages/aiohttp-3.6.2-py3.8.egg/aiohttp/web_app.py", line 458, in _handle
                                             resp = await handler(request)
                                           File "/usr/local/lib/python3.8/dist-packages/aircon-0.0.1-py3.8.egg/aircon/query_handlers.py", line 72, in property_update_handl>
                                             update = self._decrypt_and_validate(device, data)
                                           File "/usr/local/lib/python3.8/dist-packages/aircon-0.0.1-py3.8.egg/aircon/query_handlers.py", line 131, in _decrypt_and_validate
                                             raise Error('Invalid signature for %s!' % text.decode('utf-8'))
                                         UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 0: invalid continuation byte
Jan 09 17:30:03 AvirconV2 python3[2287]: E0109 17:30:03.649  web_protocol.py:355] Error handling request
                                         Traceback (most recent call last):
                                           File "/usr/local/lib/python3.8/dist-packages/aiohttp-3.6.2-py3.8.egg/aiohttp/web_protocol.py", line 418, in start
                                             resp = await task
                                           File "/usr/local/lib/python3.8/dist-packages/aiohttp-3.6.2-py3.8.egg/aiohttp/web_app.py", line 458, in _handle
                                             resp = await handler(request)
                                           File "/usr/local/lib/python3.8/dist-packages/aircon-0.0.1-py3.8.egg/aircon/query_handlers.py", line 72, in property_update_handl>
                                             update = self._decrypt_and_validate(device, data)
                                           File "/usr/local/lib/python3.8/dist-packages/aircon-0.0.1-py3.8.egg/aircon/query_handlers.py", line 131, in _decrypt_and_validate
                                             raise Error('Invalid signature for %s!' % text.decode('utf-8'))
                                         UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9a in position 3: invalid start byte
`

How can I solve it?
Thank you,

Dov
