### ISSUE TITLE
error configuration for HA addon

### ISSUE THREAD

**Issue by dovrose** [deiger/AirCon#63]
Hi,

I tsaw you started to add configuration for HA addon.
I tried to add to my HA, and recived the following error:
`21-01-10 05:32:55 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
21-01-10 05:32:55 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/deiger/AirCon repository
21-01-10 05:32:57 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/c34eddb3/aircon/config.json: does not match regular expression @ data['devices'][0]. Got '/opt/hisense:/config'
21-01-10 05:32:57 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/c34eddb3/aircon/config.json: does not match regular expression @ data['devices'][0]. Got '/opt/hisense:/config'`

?????

**Comment by deiger** [comment]
This is still WIP... 😄

**Comment by W2K** [comment]
Any ETA on when this is done. :-) I had some issues and just realized you are working on that. Just wondering if I should try to fix it myself or wait for your changes :-D

**Comment by deiger** [comment]
I'm working on it, should be done in a couple of days.
Contributions are always welcome.

**Comment by W2K** [comment]
> I'm working on it, should be done in a couple of days.
> Contributions are always welcome.

Suer thing. I am also trying to make this work on my HA. As I have free time I will also add sth myself.
Thank you for the amazing job you've done :-)

**Comment by deiger** [comment]
It should be working now, from HA as well as docker-compose.

**Comment by W2K** [comment]
Now everything works perfectly fine. From config to HA autodiscovery. :-) Thank you for the huge work you pot in that.
