### ISSUE TITLE
Home assistant 0.3.3 version config issue

### ISSUE THREAD

**Issue by W2K** [deiger/AirCon#66]
I know that the version is really really new. I have been trying to investigate the issue almost parallelly when you were working on it. Funny thing BTW ;-).

I had the same issues with the previous version on my HA:
![image](https://user-images.githubusercontent.com/9429080/104240061-c479b600-545b-11eb-8474-aff788ce6d81.png)

Something must be wrong with the config file but I did not manage to resolve this myself. Any idea? :-)

**Comment by W2K** [comment]
Added some comments in https://github.com/deiger/AirCon/commit/68411b07eb3608d9a1d5c24cae1f352ebd6a9917 on how to fix it.

**Comment by deiger** [comment]
Thanks, already debugged this. Try 0.3.4.

**Comment by W2K** [comment]
Already did. Seems that docker image is not built properly for 0.3.4 (not pushed to docker hub)
