### ISSUE TITLE
TaoTronics Humidifier TT-AH019

### ISSUE THREAD

**Issue by raphaelg** [deiger/AirCon#7]
Hi, 

It looks like the TaoTronics Humidifier TT-AH019 uses the same protocol. Would it be possible to add to the devices list ? I would do it myself but I'm not where near a programmer, just a geek ;-)

The app (com.sunvalley.sunhome  on Android) is used to control the humidifier (on/off, desired humidity. night light, timer, ect) and provides you with measured humidity.

- Devices.json

`[
    {
        "device": {
            "product_name": "Humidifier",
            "model": "AY008RTK1",
            "dsn": "__REDACTED__",
            "oem_model": "0001-0401-0001",
            "sw_version": "ADA 1.4.3-beta ameba 2018-03-28 19:20:06 8f40fe89d",
            "template_id": 8828,
            "mac": "__REDACTED__",
            "unique_hardware_id": null,
            "lan_ip": "__REDACTED__",
            "connected_at": "__REDACTED__",
            "key": __REDACTED__,
            "lan_enabled": true,
            "has_properties": true,
            "product_class": null,
            "connection_status": "Online",
            "lat": "__REDACTED__",
            "lng": "__REDACTED__",
            "locality": "__REDACTED__",
            "device_type": "Wifi"
        }
    }
]`

- Properties.json

 `[
    {
            "type": "Property",
			"property": {
            "name": "humi",
            "base_type": "integer",
            "read_only": false,
            "direction": "input",
            "scope": "user",
            "data_updated_at": "__REDACTED__",
            "key": 145881465,
            "device_key": __REDACTED__,
            "product_name": "Humidifier",
            "track_only_changes": false,
            "display_name": "humi",
            "host_sw_version": false,
            "time_series": false,
            "derived": false,
            "app_type": null,
            "recipe": null,
            "value": 0,
            "denied_roles": [],
            "ack_enabled": false,
            "retention_days": 30,
            "ack_status": null,
            "ack_message": null,
            "acked_at": null
        }
    },
    {
        "property": {
            "type": "Property",
            "name": "mist",
            "base_type": "integer",
            "read_only": false,
            "direction": "input",
            "scope": "user",
            "data_updated_at": "__REDACTED__",
            "key": 145881466,
            "device_key": __REDACTED__,
            "product_name": "Humidifier",
            "track_only_changes": false,
            "display_name": "mist",
            "host_sw_version": false,
            "time_series": false,
            "derived": false,
            "app_type": null,
            "recipe": null,
            "value": 3,
            "denied_roles": [],
            "ack_enabled": false,
            "retention_days": 30,
            "ack_status": null,
            "ack_message": null,
            "acked_at": null
        }
    },
    {
        "property": {
            "type": "Property",
            "name": "mistSt",
            "base_type": "integer",
            "read_only": true,
            "direction": "output",
            "scope": "user",
            "data_updated_at": "__REDACTED__",
            "key": 145881467,
            "device_key": __REDACTED__,
            "product_name": "Humidifier",
            "track_only_changes": false,
            "display_name": "mistSt",
            "host_sw_version": false,
            "time_series": false,
            "derived": false,
            "app_type": null,
            "recipe": null,
            "value": 1,
            "denied_roles": [],
            "ack_enabled": false,
            "retention_days": 30,
            "ack_status": null,
            "ack_message": null,
            "acked_at": null
        }
    },
    {
        "property": {
            "type": "Property",
            "name": "realhumi",
            "base_type": "integer",
            "read_only": true,
            "direction": "output",
            "scope": "user",
            "data_updated_at": "__REDACTED__",
            "key": 145881468,
            "device_key": __REDACTED__,
            "product_name": "Humidifier",
            "track_only_changes": false,
            "display_name": "realhumi",
            "host_sw_version": false,
            "time_series": false,
            "derived": false,
            "app_type": null,
            "recipe": null,
            "value": 48,
            "denied_roles": [],
            "ack_enabled": false,
            "retention_days": 30,
            "ack_status": null,
            "ack_message": null,
            "acked_at": null
        }
    },
    {
        "property": {
            "type": "Property",
            "name": "remain",
            "base_type": "integer",
            "read_only": true,
            "direction": "output",
            "scope": "user",
            "data_updated_at": "__REDACTED__",
            "key": 145881469,
            "device_key": __REDACTED__,
            "product_name": "Humidifier",
            "track_only_changes": false,
            "display_name": "remain",
            "host_sw_version": false,
            "time_series": false,
            "derived": false,
            "app_type": null,
            "recipe": null,
            "value": 0,
            "denied_roles": [],
            "ack_enabled": false,
            "retention_days": 30,
            "ack_status": null,
            "ack_message": null,
            "acked_at": null
        }
    },
    {
        "property": {
            "type": "Property",
            "name": "switch",
            "base_type": "boolean",
            "read_only": false,
            "direction": "input",
            "scope": "user",
            "data_updated_at": "__REDACTED__",
            "key": 145881470,
            "device_key": __REDACTED__,
            "product_name": "Humidifier",
            "track_only_changes": false,
            "display_name": "switch",
            "host_sw_version": false,
            "time_series": false,
            "derived": false,
            "app_type": null,
            "recipe": null,
            "value": 1,
            "denied_roles": [],
            "ack_enabled": false,
            "retention_days": 30,
            "ack_status": null,
            "ack_message": null,
            "acked_at": null
        }
    },
    {
        "property": {
            "type": "Property",
            "name": "temp",
            "base_type": "integer",
            "read_only": true,
            "direction": "output",
            "scope": "user",
            "data_updated_at": "null",
            "key": 145881471,
            "device_key": __REDACTED__,
            "product_name": "Humidifier",
            "track_only_changes": false,
            "display_name": "temp",
            "host_sw_version": false,
            "time_series": false,
            "derived": false,
            "app_type": null,
            "recipe": null,
            "value": null,
            "denied_roles": [],
            "ack_enabled": false,
            "retention_days": 30
        }
    },
    {
        "property": {
            "type": "Property",
            "name": "timer",
            "base_type": "integer",
            "read_only": false,
            "direction": "input",
            "scope": "user",
            "data_updated_at": "__REDACTED__",
            "key": 145881472,
            "device_key": __REDACTED__,
            "product_name": "Humidifier",
            "track_only_changes": false,
            "display_name": "timer",
            "host_sw_version": false,
            "time_series": false,
            "derived": false,
            "app_type": null,
            "recipe": null,
            "value": 0,
            "denied_roles": [],
            "ack_enabled": false,
            "retention_days": 30,
            "ack_status": null,
            "ack_message": null,
            "acked_at": null
        }
    },
    {
        "property": {
            "type": "Property",
            "name": "version",
            "base_type": "string",
            "read_only": true,
            "direction": "output",
            "scope": "user",
            "data_updated_at": "__REDACTED__",
            "key": 145881473,
            "device_key": __REDACTED__,
            "product_name": "Humidifier",
            "track_only_changes": true,
            "display_name": "version",
            "host_sw_version": true,
            "time_series": false,
            "derived": false,
            "app_type": null,
            "recipe": null,
            "value": "universal 05.008.001",
            "denied_roles": [],
            "ack_enabled": false,
            "retention_days": null,
            "ack_status": null,
            "ack_message": null,
            "acked_at": null
        }
    },
    {
        "property": {
            "type": "Property",
            "name": "water",
            "base_type": "boolean",
            "read_only": true,
            "direction": "output",
            "scope": "user",
            "data_updated_at": "__REDACTED__",
            "key": 145881474,
            "device_key": __REDACTED__,
            "product_name": "Humidifier",
            "track_only_changes": false,
            "display_name": "water",
            "host_sw_version": false,
            "time_series": false,
            "derived": false,
            "app_type": null,
            "recipe": null,
            "value": 0,
            "denied_roles": [],
            "ack_enabled": false,
            "retention_days": 30,
            "ack_status": null,
            "ack_message": null,
            "acked_at": null
        }
    },
    {
        "property": {
            "type": "Property",
            "name": "workmode",
            "base_type": "integer",
            "read_only": false,
            "direction": "input",
            "scope": "user",
            "data_updated_at": "__REDACTED__",
            "key": 145881475,
            "device_key": __REDACTED__,
            "product_name": "Humidifier",
            "track_only_changes": false,
            "display_name": "workmode",
            "host_sw_version": false,
            "time_series": false,
            "derived": false,
            "app_type": null,
            "recipe": null,
            "value": 0,
            "denied_roles": [],
            "ack_enabled": false,
            "retention_days": 30,
            "ack_status": null,
            "ack_message": null,
            "acked_at": null
        }
    }
]`

- Lan.json

`{
    "lanip": {
        "lanip_key_id": __REDACTED__,
        "lanip_key": "__REDACTED__",
        "keep_alive": 30,
        "auto_sync": 1,
        "status": "enable"
    }
}`

Many thanks for your project !

**Comment by deiger** [comment]
Hi,

Sure, I've added it to the query CLI.
I'll add the properties and update.

**Comment by raphaelg** [comment]
Great !
Thank you very much !

**Comment by deiger** [comment]
OK, added these properties. Check it out. You should run it with --device_type=humidifier.
I'm not sure about the default values, and it seems that some of the properties should have an enum mapping, like workmode.

**Comment by raphaelg** [comment]
It works great ! Thank you !
I got the values:
- MistST (Mist Status) 0: On 1:Off
- Workmode 0: Normal 1:Nightlight 2:Sleep
- Mist 0:Low 1:Medium 2:High
- Humi 0:Humidistat off Value(integer):Humidistat desired humidity
- Timer 0:Off 1:On
- Remain (If Timer on) Value(Integer) Remaining time
- Switch On or Off
- Water False:Water Level OK True: Needs water (counter intuitive this one!)

**Comment by deiger** [comment]
Added all the relevant enums. Please try it now.

**Comment by raphaelg** [comment]
All is good. 
Thank you.

**Comment by YankoIvanov** [comment]
Hi @raphaelg, how did you set up the humidifier in Home Assistant? I would really like to do that as well but am not clear on the process. Would you mind outlining the steps you took?
