### ISSUE TITLE
mqtt commands fgl-air

### ISSUE THREAD

**Issue by Corne008** [deiger/AirCon#71]
Hi Deiger,
One more question for now ;-).
I figured out the mosquitto_pub command for the paramaters you mentioned in another issue.
mosquitto_pub -h 192.168.2.63 -u mqtt -P welkom01 -t Airco_no1/a0c234cb4b2/operation_mode/command -m off
to turn the AC off.

BUT... what is the command to get the settings/ status of the device? I want to send a command to see the settings via MQTT?

Thnx

**Comment by deiger** [comment]
For status in MQTT you need to subscribe to the relevant topic, e.g. Airco_no1/a0c234cb4b2/operation_mode/status for the operation mode.
You can see the entire list using MQTT Explorer.

**Comment by Corne008** [comment]
Thnx, but I forget to mention that I already have the sub running. When a status is set using pub, I see the return status passing... but I'm looking for a command to send with pub that returns the status of the device through mqtt. Just like the curl status returns a json, but unfortunately no mqtt message.
Thnx again.

**Comment by deiger** [comment]
I'm afraid that's not what MQTT is for. Sorry.

**Comment by Corne008** [comment]
Ok, thanks for your help and answers
