### ISSUE TITLE
Turning on heat does not keep previous temperature 

### ISSUE THREAD

**Issue by rotem925** [deiger/AirCon#72]
Hi @deiger ,
When setting to heat(maybe even cool)
The AC turns on, I hear several beeps(supposed to hear only one I guess) and then the temp changes to 23c.
Previously the AC was set to 25.
It looks like there are other commands that are sent to the AC.

**Comment by deiger** [comment]
Setting the work mode sends 2 commands, one is `t_power=true` and the other is `t_work_mode=HEAT`. See here: https://github.com/deiger/AirCon/blob/master/aircon/aircon.py#L246. This is because HA doesn't have the interface for power ON/OFF
It's not supposed to update the temp. That said, I believe the AC is internally storing different temperatures for each work mode. Could that be the case here?

**Comment by rotem925** [comment]
This can be the case..
Though I can see that the AC starts with 25c, then I hear beep and it changes to 23.
Unless, the power on just turn on the last state, and the heat command, changes the mode and the temperature internally in the AC, as you described.

**Comment by deiger** [comment]
Yes, the power on command just turns on the A/C.

**Comment by rotem925** [comment]
So what if the following scenario happens:

1. Setting the mode just turn on the AC.
2. if it is not already on the selected mode, it changes the mod.

What do you think?

**Comment by dvdavide** [comment]
Before the MQTT auto discovery was available I used the manual configuration, and had a separate switch for power, sitting right below the climate dial. There's nothing stopping you from making one too, it doesn't clash with the climate entity. Configuration is something like this, in the switch section:
```
- platform: mqtt
  unique_id: bedroom_ac_power
  name: "Bedroom AC Power"
  command_topic: "hisense_ac/<macaddress>/t_power/command"
  state_topic: "hisense_ac/<macaddress>/t_power/status"
  payload_on: "on"
  payload_off: "off"
  state_on: "on"
  state_off: "off"
```

**Comment by rotem925** [comment]
Thanks!
I'll take your suggestion.
