### ISSUE TITLE
mqtt retain status updates

### ISSUE THREAD

**Issue by rotem925** [deiger/AirCon#76]
Hi @deiger 
I've noticed that sometimes, the hisense_ac topic is empty (just the LWT=online is present)
I think when updating the status, this should be with the retain flag=True?
Else, the broker seems to be out of sync with the status, if there was a restart of the broker.

What do you think?

**Comment by rotem925** [comment]
Not sure that the only issue here.
I can see in the logs that there are no logs at all for about 3 hours..

**Comment by deiger** [comment]
No logs for 3 hours is really strange, sounds like the process got stuck. Even if nothing else happens, you should still see the server querying the A/C for all properties every 10 minutes.
Are you sure that on a broker restart all previous updates are gone?

**Comment by rotem925** [comment]
Yes, pretty sure.
Just restarted the broker and looked at it through MQTT Explorer.
I think as you said, the whole process was stuck..

**Comment by rotem925** [comment]
@deiger I think that this happens when some of the ACs are down. It looked like it is not stable then.
Just had a case where all the ACs are connected and the system looks pretty stable.

**Comment by rotem925** [comment]
@deiger, latest 0.3.7 release does not publish to topic if ac is not available.

I have started the container and it does not set the available topic on startup.
I guess it is skipped if the device is not available on startup.

**Comment by deiger** [comment]
Try 0.3.7.1, I've fixed the retry logic.

**Comment by wifi75** [comment]
On HA something doesn't work :

**Comment by deiger** [comment]
@wifi75 on which version are you, and how does your config look?
Please make sure you are on `0.3.7.2`, and that the specified port is _not_ 1883 (that is the port used by MQTT).

**Comment by wifi75** [comment]
@deiger I'm stupid, I change de port and now work! 
Update version it's not available at moment, Ha it showes me only 0.3.7 version

**Comment by deiger** [comment]
HA auto-updates its list every day or so. You can kick-start it by going to the Add-on Store and clicking reload from the menu.
In any case, the small update only includes fixes for the case of a stuck A/C, so it's not urgent.

**Comment by rotem925** [comment]
I think this issue is solved...
Closing...
