### ISSUE TITLE
add support for Electra AC models

### ISSUE THREAD

**Issue by jossef** [deiger/AirCon#77]
![image](https://user-images.githubusercontent.com/1287098/106264400-44f72f80-622e-11eb-8956-d7144a9ad849.png)

**Comment by deiger** [comment]
Which module does the Electra A/C use? IIRC they are manufactured by Midea, so it's unlikely that they use the same protocol.
Please take a look at the module itself (connected under the hood on the righthand side), and see if you can get any info.

**Comment by deiger** [comment]
Just had a look at their app. Although Midea has signed an agreement with Ayla Networks in 2016, unfortunately Electra is not using their API.

**Comment by jossef** [comment]
What about doing some RE and invoking their REST API calls from the mobile app?
I can offer to do this and submit a PR

![image](https://user-images.githubusercontent.com/1287098/106353746-77b82b00-62f5-11eb-8d18-43842d6523ac.png)

**Comment by deiger** [comment]
I have a strong preference against relying on the cloud, both for performance reasons and security.
As I said before, the protocol of Electra is entirely different, so I'm not sure it would be a good fit. If you manage to get it working without wrecking havoc in the code, I'd be happy to merge a PR.
