### ISSUE TITLE
query_cli.py not found

### ISSUE THREAD

**Issue by akhtar321h** [deiger/AirCon#78]
I am not getting query_cli.py file.
Any help is appreciated.

**Comment by deiger** [comment]
You don't need it anymore.
The new command for discovery is `python3 -m aircon discovery tornado-us foo@example.com my_pass`
How are you planning to use it? If in HomeAssistant, just use the add-on. Otherwise prefer using the docker. Both options will do the discovery for you on the first run.

**Comment by akhtar321h** [comment]
First i want to try manually from CLI.
Is this command works from CLI?

**Comment by deiger** [comment]
Yes, follow the instructions [here](https://github.com/deiger/AirCon#run-the-ac-control-server-manually).
