### ISSUE TITLE
AEH-W4E1

### ISSUE THREAD

**Issue by dvdavide** [deiger/AirCon#8]
I would like to try if your clever script works on the "E" variation of the wifi interface.
I tried connecting to the AC with the Hi-Smart AC app but sadly it didn't detect the module. I had to use the [HiSmart Life](https://play.google.com/store/apps/details?id=com.hisense.hismartinternationalforandroid&hl=en) app instead.
It would be great if you could have a look at it and see if there's any chance to make it work with your script; from the little analysis I could perform, it seems to connect to Ayla networks so maybe there's a little hope. But I don't know where to extract the secret codes to emulate the app in query_cli.py so I'm basically stuck.
Thanks in advance for your help and again congratulations on a very useful bit of code.

**Comment by deiger** [comment]
I'll try prying into that app.

**Comment by deiger** [comment]
OK, I'm not sure the protocol itself is the same, but the query CLI should work now - please try with `--app hisense-eu`

**Comment by dvdavide** [comment]
Fantastic! I'll run a test and report back. Thank you!

**Comment by toporovskii** [comment]
Hi, 
I have same AEH-W4E1 modue and looks like it should work with your app. However my module works with another app Hismart Living https://play.google.com/store/apps/details?id=com.smart.international2
Servers matched with hisense-eu I'm able to authorize with query_cli but no devices in the list. 
looks like app secret is different. 

Could you please look at this app as well?

**Comment by toporovskii** [comment]
It was  wrong password. 
Now it's working 
Fill free to add one more application to your code 

appKey = "Hismart-fA-id"
appSecret = "Hismart-MAfpBGGmZcQcCCsiDYR3kY-oKZg"
Servers: EU
Link to App: https://play.google.com/store/apps/details?id=com.smart.international2

**Comment by toporovskii** [comment]
Thanks a lot. 
Now I finaly can add my four ACs to HomeAssistant.

**Comment by deiger** [comment]
Sure. Added it now to the CLI.

**Comment by scaramatto** [comment]
> Thanks a lot.
> Now I finaly can add my four ACs to HomeAssistant.

Sorry, i have AEH-W4B1 can you help me to add in HomeAssitant? PLS!!!

**Comment by deiger** [comment]
@toporovskii, if you can provide your YAML files I'd be happy to add them for the others here to use. I'm afraid I do not use HA.

**Comment by ftp21** [comment]
I'm in a strange situation. I removed my module from HiSense app and i try to reassociate to my new Wifi Network. Module can auth to my wifi netowk but can't readd to Ayla/Hisense cloud.
Now i have the module connected to my network and i can ping and navigate it but it hasn't any registration token and i can't remove the Wifi Profile (FIrmware BUG??).


I try to read le Web Server lib (https://github.com/kaiguarensheng/redsea/tree/master/component/common/ayla/libada) but all important pages is allowed only after key exchange. If i go to http://module/client or to http://module/regtoken.json there isn't any token.

There is any fix or i need to rebuy newone?

Last possibile chance is read the SPI Flash and try to patch the "reset.json" page to be accessibile without key_exchange

**Comment by kekkodance** [comment]
@ftp21 i am almost in your same situation except the device gives me a key to put in a "Device Registration" field. /client and /regtoken work but i have this key i don't know what to do with.

**Comment by cvladan** [comment]
For anyone still landing here with the AEH-W4E1 module — I made a fork of this project (with a lot of help from AI) that works as a native HACS integration for Home Assistant. No MQTT, no Docker, no YAML configuration needed. Just add it as a custom repository in HACS.

In case it's helpful: https://github.com/cvladan/hassio-hacs-hisense-aircon
