### ISSUE TITLE
"online" status infinity loop?

### ISSUE THREAD

**Issue by Csstenersen** [deiger/AirCon#83]
Hi.
I'm running this on homeassistant with "fglaiR" and it works great a while, but suddenly the MQTT message "online" keeps publishing several times pr.second under topic: /available/status until my homeassistant freezes.

Below is a snipp from my debug in node-red:

![image](https://user-images.githubusercontent.com/48843914/107871938-6dc22a80-6ea6-11eb-8168-f1d931afd2aa.png)

Anyone have any fixes or something?

**Comment by deiger** [comment]
It never sent to that frequently for me.
In any case, I've changed it to update the availability status only on change. Please try the recent version (0.3.9).

**Comment by Csstenersen** [comment]
Log in HomeAssistant still flooded with [keepAlive]

![image](https://user-images.githubusercontent.com/48843914/111075628-2b156180-84e9-11eb-9d3d-b9404d09fc24.png)

**Comment by deiger** [comment]
Why are you running it with `log_level: DEBUG`?

**Comment by Csstenersen** [comment]
Cause I want to maby see why the addon fails to run properly. After you set precision to 0.1 the values does not appear correct. When i set 21 degress in Hass it returns 2degress after anfew seconds

Mvh
Christopher Stenersen
Tlf 95034829

Sendt fra min telefon
________________________________
Fra: Dror Eiger ***@***.***>
Sendt: Sunday, March 14, 2021 8:17:04 PM
Til: deiger/AirCon ***@***.***>
Kopi: Csstenersen ***@***.***>; Author ***@***.***>
Emne: Re: [deiger/AirCon] "online" status infinity loop? (#83)


Why are you running it with log_level: DEBUG?
