### ISSUE TITLE
Wrong temperature with fglair

### ISSUE THREAD

**Issue by manderino1** [deiger/AirCon#85]
Hi, i configured successfully my two devices in home assistant, I have climates with fglair.
Now with curl i see this status:
`{"devices": [{"ip": "192.168.1.81", "props": {"operation_mode": "OFF", "fan_speed": "AUTO", "adjust_temperature": 25, "af_vertical_move_step1": 3, "af_horizontal_move_step1": 3, "economy_mode": "OFF"}}, {"ip": "192.168.1.66", "props": {"operation_mode": "HEAT", "fan_speed": "AUTO", "adjust_temperature": 210, "af_vertical_direction": 4, "af_vertical_swing": "OFF", "af_horizontal_direction": 3, "af_horizontal_swing": "OFF", "economy_mode": "OFF"}}]}`
Obviously given that the temperature is in Celsius the 210 on the second one is wrong, it should be 21

Surprisingly, I see that 210 on home assistant but not the other temperature, I can correctly turn on and off the climates from home assistant, but I cannot change the temperature
Do you know what could be wrong? Thank you!

![Cattura](https://user-images.githubusercontent.com/44238126/108988214-7da2f100-7694-11eb-8c8a-23cc79dbb9dd.PNG)
![Cattura2](https://user-images.githubusercontent.com/44238126/108988225-809de180-7694-11eb-8022-e6992fba1984.PNG)

**Comment by manderino1** [comment]
Slight update
If I run it as a service and I check the log with status I get the same error that was happening at @Corne008 in issue #53
I get the error from the parse message that was added in the following commit

**Comment by deiger** [comment]
I'm not sure I understand, #53 has been closed.
Could you please detail what the log states for you?
Seems really strange that adjust_temperature would return 210. I've had a look at the app's javascript code, and it doesn't seem to multiply the value.

**Comment by manderino1** [comment]
This is the log after the start

```
E0227 10:01:55.614  query_handlers.py:75] Failed to parse property.
Traceback (most recent call last):
  File "/usr/bin/pythontidy", line 9, in <module>
    load_entry_point('PythonTidy==1.21', 'console_scripts', 'pythontidy')()
  File "build/bdist.linux-x86_64/egg/runner.py", line 31, in main
  File "build/bdist.linux-x86_64/egg/PythonTidy.py", line 4809, in tidy_up
  File "/usr/lib64/python2.7/compiler/transformer.py", line 51, in parse
    return Transformer().parsesuite(buf)
  File "/usr/lib64/python2.7/compiler/transformer.py", line 128, in parsesuite
    return self.transform(parser.suite(text))
  File "<string>", line 1
    query_handlers.py:75] Failed to parse property.
                     ^
SyntaxError: invalid syntax
```

**Comment by Csstenersen** [comment]
@manderino1 I also got this issue but i just assumed that this was the temperature multiplied by 10 in my AC.
My solution was to make a new mqtt climate entity in home-assistant an then I divided and multiplied the mqtt values in node-red to to pass between my new mqtt climate entity and hisense climate entity. 
But I'm having problems with this addon cause it seems to freeze and sends out a continius stream of "online" messages on mqtt and my ac can not be controlled.

**Comment by deiger** [comment]
Please try the latest version, I've changed fglair to divide the temperature by 10.

**Comment by christoph-ng** [comment]
The fix doesn't work correct, decimal values are not set correctly, see the log above:

```
I0628 20:17:03.327  mqtt_client.py:37] MQTT message Topic: hisense_ac/a0cc2be7a43b/adjust_temperature/command, Payload b'25.5'
D0628 20:17:03.328  notifier.py:112] [KeepAlive] Sending PUT http://192.168.0.99/local_reg.json {"local_reg": {"ip": "192.168.0.77", "notify": 1, "port": 1883, "uri": "/local_lan"}}
D0628 20:17:03.338  query_handlers.py:122] Encrypting: {"seq_no": 8, "data": {"properties": [{"property": {"base_type": "integer", "name": "adjust_temperature", "value": 260, "id": "UhTgWh6W"}}]}}
I0628 20:17:03.339  web_log.py:206] 192.168.0.99 [28/Jun/2021:20:17:03 +0000] "GET /local_lan/commands.json HTTP/1.1" 200 417 "-" "-"
D0628 20:17:03.340  notifier.py:85] [KeepAlive] Waiting for notification or timeout
I0628 20:17:04.727  query_handlers.py:136] Decrypted: {"seq_no":8,"data":{"name":"adjust_temperature","value":260}}
```
