### ISSUE TITLE
Can not Start or edit config

### ISSUE THREAD

**Issue by zachaj77** [deiger/AirCon#88]
Hi,

I installed, but the configuration won't let me save. Every time I try, it changes back to username = null, preventing me from Starting the Add-on.

Installed via HA as in documentation.

ZachAJ

**Comment by nikogusm** [comment]
Hi Zach, i have the same exact problem. I was hoping to find the config file in the filesystem to edit it manually from the command line but I haven't found the path of AirCon in the home assistant folders so I am stuck in the same exact problem.

I have tried to install it both in Home Assistant OS and Home Assistant Supervised (running on Pi OS): they have the identical issue. 

I started and configured MQTT as minimum requirement but it has not solved it.

What we can do?

Nicola

**Comment by deiger** [comment]
This sounds really strange. This has never been an issue, so it might be a problem in HA's parsing.
I deleted the default values for the app. Could you please try again?

**Comment by nikogusm** [comment]
I tried now and the issue is still there. When I click save, everything I type turns back to the original file and I cannot start the application.

**Comment by deiger** [comment]
Is this still an issue even if you upgrade to the latest version? I'm not sure what's wrong. Can you paste here your config file (with the username and password replaced)?

**Comment by Sablic** [comment]
The issue still in place. At least at 0.3.9.

**Comment by nikogusm** [comment]
Yes. Today I updated home assistant to core 2021.3.4 and AirCon to 0.3.9 but the issue is still here.

Here is my config file that after updating to this version has less lines (???)

`log_level: INFO
mqtt_host: core-mosquitto
mqtt_user: null
mqtt_pass: null
port: null
`

and when I click save it reverts to original.
Nicola

**Comment by Sablic** [comment]
BTW. I have checked everything and it seems like docker image pulled. However container is not created. When I tried to create it manually it failed with /data/options.json not existent

**Comment by fixsssator** [comment]
Thank you for your work. But there is an issue jq: error: Could not open file /data/options.json: No such file or directory

**Comment by papka1974** [comment]
Same here. I'm new in Home assistant and thought it's my fault, but seems not. Inside UI configuration not changeable. Under /data folder /c34eddb3_hisense_ac created but it's empty. Tried to place options.json file there - nothing.

**Comment by papka1974** [comment]
I got it working. I took full options.json file content and pasted it in Configuration page, updated values of course, pressed Save and everything works.

**Comment by fixsssator** [comment]
> I got it working. I took full options.json file content and pasted it in Configuration page, updated values of course, pressed Save and everything works.

You are amazing, thank you for solution.

**Comment by zachaj77** [comment]
> I got it working. I took full options.json file content and pasted it in Configuration page, updated values of course, pressed Save and everything works.

Worked for me too. Thanks!

**Comment by roxyamaha** [comment]
I have same problem with launching my hisense_ac container
`jq: error: Could not open file /data/options.json: No such file or directory`
@papka1974 where exactly did you paste options.json contents?
I'm trying to run it as docker container.

**Comment by papka1974** [comment]
> I have same problem with launching my hisense_ac container `jq: error: Could not open file /data/options.json: No such file or directory` @papka1974 where exactly did you paste options.json contents? I'm trying to run it as docker container.

I pasted full content of options.json file in plugin configuration page.

**Comment by roxyamaha** [comment]
Hm, okay. But this doesn't work for me since I'm using containers and need to run hisense_ac from container.
