### ISSUE TITLE
Undiscovered Devices

### ISSUE THREAD

**Issue by gtrizzo** [deiger/AirCon#90]
Hi, I have 2 hisense AC with the same Aeh-W4b1 but module, only one is recognized ... Do you know how to recognize them all?

Thanks for your help

**Comment by FedeGiobbe** [comment]
> Hi, I have 2 hisense AC with the same Aeh-W4b1 but module, only one is recognized ... Do you know how to recognize them all?
> 
> Thanks for your help

Same issue here...

**Comment by gtrizzo** [comment]
> > Hi, I have 2 hisense AC with the same Aeh-W4b1 but module, only one is recognized ... Do you know how to recognize them all?
> > Thanks for your help
> 
> Same issue here...

Ciao FedeGiobbe,
suppongo tu sia italiano quindi ti scrivo in italiano, se poi mi fanno storie scriverò anche in inglese, io il problema l'ho risolto, non so esattamente dirti come ma, mi sembra, di aver fatto questa procedura:

1. Arrestato servizio Aircon da Supervisor
2. Cancellata cartella Hisnse dentro Config
3. Riavviato servizio Aircon.

Lo so, non è molto, ma prova e riprova alla fine me li ha riconosciuti tutti e due, una cosa che forse ho capito è che ha bisogno che sia già in esecuziuone Mqtt prima di avviare Aircon.

Spero di essrti stato utile.

**Comment by deiger** [comment]
Indeed, if you add a new A/C after the service is already running, the best way to kick discovery again is to delete the config file.
Note that you do not need to stop the service before the deletion, the file is not "locked". Just delete it and restart the service.

**Comment by gtrizzo** [comment]
Great, thanks, solved

Il giorno dom 28 mar 2021 alle ore 09:32 Dror Eiger <
***@***.***> ha scritto:

**Comment by FedeGiobbe** [comment]
Solved for me too, but I also had to delete and pair the ACs again from the app. Without repeating the pairing procedure, aricon kept on logging that it was unable to get the MAC address of one of my ACs.
Thanks!

**Comment by cvladan** [comment]
For anyone dealing with multiple AEH-W4B1 units in Home Assistant: I made a fork of this project that works as a proper HACS integration and handles multiple devices natively — no Docker or MQTT setup needed.

https://github.com/cvladan/hassio-hacs-hisense-aircon
