### ISSUE TITLE
Configuration edits do not save in Home Assistant

### ISSUE THREAD

**Issue by YankoIvanov** [deiger/AirCon#94]
Hi, I am trying to do the Home Assistant add-on install but am getting stuck on step 5 of the instructions: 
5. Update the configuration as detailed within the add-on 

When I edit the configuration for the add-on and hit save, it reverts to the default config (as below) and any changes are lost: 
`log_level: INFO
mqtt_host: core-mosquitto
mqtt_user: null
mqtt_pass: null
port: null`

I am running on the latest HomeAssistant (2021.4.6) on a dedicated Raspberry Pi 4 8gb. 

Any ideas what may be going wrong?

**Comment by macteo** [comment]
Same issue here.
Same Raspberry Pi 4 8Gb configuration

**Comment by macteo** [comment]
Seems the same issue reported on #88

**Comment by macteo** [comment]
I can confirm that pasting the properly modified [options.json](https://github.com/deiger/AirCon/blob/master/options.json) configuration file solves the issue.


```
  "app": [
    {
      "username": "<app username>",
      "password": "<app password>",
      "code": "<app code>"
    }
  ],
  "log_level": "INFO",
  "mqtt_host": "localhost",
  "mqtt_user": "<mqtt username>",
  "mqtt_pass": "<mqtt password>",
  "port": 8888
}
```

**Comment by YankoIvanov** [comment]
Thanks for this! Can you elaborate a bit though. I'm pasting the above into the configuration page of the add on and I'm getting a message at the bottom saying "invalid YAML" and the Save button is greyed out. So I'm pasting json into something expecting YAML. Am I not pasting in the right place?

**Comment by YankoIvanov** [comment]
Tried copying the full YAML in the documentation with the appropriate value edits and that seems to have saved it.
